### ISSUE TITLE
Method stopStep end with exception

### ISSUE THREAD

**Issue by chadaeva** [allure-framework/allure2#1014]
**Describe the bug**
Allure.getLifecycle().stopStep() end with exception:
java.lang.IllegalStateException: Can not cast io.qameta.allure.model.TestResult@32d0d7eb to class io.qameta.allure.model.StepResult
        at io.qameta.allure.internal.AllureStorage.cast(AllureStorage.java:131)
        at io.qameta.allure.internal.AllureStorage.lambda$get$1(AllureStorage.java:118)
        at java.util.Optional.map(Optional.java:215)
        at io.qameta.allure.internal.AllureStorage.get(AllureStorage.java:118)
        at io.qameta.allure.internal.AllureStorage.getStep(AllureStorage.java:97)
        at io.qameta.allure.AllureLifecycle.updateStep(AllureLifecycle.java:220)
        at io.qameta.allure.AllureLifecycle.lambda$updateStep$14(AllureLifecycle.java:216)
        at java.util.Optional.ifPresent(Optional.java:159)
        at io.qameta.allure.AllureLifecycle.updateStep(AllureLifecycle.java:216)
        at io.qameta.allure.cucumberjvm.AllureCucumberJvm.result(AllureCucumberJvm.java:172)

| Allure version | 2.13.0 |
| --- | --- |
| Test framework | junit4@6.8 |
| Allure adaptor | allure-cucumber-jvm@2.9.0 |

**Comment by baev** [comment]
this error means that you are trying to stop step without starting it (for example, you'll get this message if call `stopStep()` without calling `startStep()` before)

**Comment by chadaeva** [comment]
error repeated
code:
String uuid = UUID.randomUUID().toString();
StepResult stepResult = new StepResult();
stepResult.setName("step");
Allure.getLifecycle().startStep(uuid, stepResult);

Allure.getLifecycle().updateStep(uuid, s -> {
    s.setStatus(Status.BROKEN);
            s.setStatusDetails(statusDetails);
            s.setStop(System.currentTimeMillis());
});
Allure.getLifecycle().stopStep(uuid);
