### ISSUE TITLE
Seems that label feature not rendering

### ISSUE THREAD

**Issue by EltonZhong** [allure-framework/allure2#1043]
The xml is generated by allure-mocha, and when transferd to html, label feature is missing.
```xml
 <?xml version='1.0'?>
 <ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1578913462617' stop='1578913466708'>
     <name>Simple login</name>
     <title>Simple login</title>
     <test-cases>
         <test-case start='1578913463776' status='broken' stop='1578913466644'>
             <name>I believe I can fly</name>
             <title>I believe I can fly</title>
             <labels>
                 <label name='feature' value='Simple loginfeature'/>
             </labels>
             <parameters>
                 <parameter kind='argument' name='env' value='test'/>
                 <parameter kind='argument' name='religion' value='ph'/>
             </parameters>
             <steps/>
             <attachments/>
             <failure>
                 <message>First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.</message>
                 <stack-trace>TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
                     at Function.Buffer.from (buffer.js:183:11)
                     at screenshot (common/hack_mocha.js:51:42)
                     at &lt;anonymous>
                     at process._tickCallback (internal/process/next_tick.js:189:7)</stack-trace>
             </failure>
             <description type='text'>Simple loginname</description>
         </test-case>
     </test-cases>
 </ns2:test-suite>
```

Report is like below:
![!img](https://user-images.githubusercontent.com/20570738/72251835-61cbbf80-3639-11ea-896f-86524459d3f7.png)

**Comment by EltonZhong** [comment]
the Feature label is not showing in the html report.

**Comment by baev** [comment]
closed as stale
