### ISSUE TITLE
Got exception when allure open browser

### ISSUE THREAD

**Issue by askfor** [allure-framework/allure2#1122]
Got this exception when allure trying to open the browser.
```

Exception in thread "main" java.lang.UnsupportedOperationException: The BROWSE action is not supported on the current platform!
        at java.awt.Desktop.checkActionSupport(Desktop.java:221)
        at java.awt.Desktop.browse(Desktop.java:380)
        at io.qameta.allure.Commands.openBrowser(Commands.java:213)
        at io.qameta.allure.Commands.open(Commands.java:138)
        at io.qameta.allure.Commands.serve(Commands.java:122)
        at io.qameta.allure.CommandLine.run(CommandLine.java:144)

```
The way allure check if can open browser is supported is different from awt.Desktop.

allure's way:
https://github.com/allure-framework/allure2/blob/59384bd81c6cd82c0258db84885b0b6b5d46ed4d/allure-commandline/src/main/java/io/qameta/allure/Commands.java#L220

awt.Desktop's way
`this.checkActionSupport(Desktop.Action.BROWSE);`

I think it should be the same.

**Comment by smubarak** [comment]
try - http://localhost:port-number

**Comment by siddharthmittal97** [comment]
Hello All

I am getting the following error

Please tell me the solution .How to fix it

Browse operation is not supported on your platform.You can use the link below to open the report manually.
java.lang.UnsupportedOperationException: The BROWSE action is not supported on the current platform!
at java.awt.Desktop.checkActionSupport(Desktop.java:221)
at java.awt.Desktop.browse(Desktop.java:380)
at io.qameta.allure.Commands.openBrowser(Commands.java:221)
at io.qameta.allure.Commands.open(Commands.java:152)
at io.qameta.allure.Commands.serve(Commands.java:135)
at io.qameta.allure.CommandLine.run(CommandLine.java:167)
at java.util.Optional.orElseGet(Optional.java:267)
at io.qameta.allure.CommandLine.main(CommandLine.java:92)

Your help would be highly appreciated !!

**Comment by welshy557** [comment]
> Hello All
> 
> I am getting the following error
> 
> Please tell me the solution .How to fix it
> 
> Browse operation is not supported on your platform.You can use the link below to open the report manually. java.lang.UnsupportedOperationException: The BROWSE action is not supported on the current platform! at java.awt.Desktop.checkActionSupport(Desktop.java:221) at java.awt.Desktop.browse(Desktop.java:380) at io.qameta.allure.Commands.openBrowser(Commands.java:221) at io.qameta.allure.Commands.open(Commands.java:152) at io.qameta.allure.Commands.serve(Commands.java:135) at io.qameta.allure.CommandLine.run(CommandLine.java:167) at java.util.Optional.orElseGet(Optional.java:267) at io.qameta.allure.CommandLine.main(CommandLine.java:92)
> 
> Your help would be highly appreciated !!

I'm getting this too
