### ISSUE TITLE
Can not generate Allure Reports on Jenkins

### ISSUE THREAD

**Issue by Jason-Giron** [allure-framework/allure2#1501]
Jenkins Version: Jenkins 2.303.3

Allure Command-Line: 2.13.4

Allure Plugin: 2.29.0

```
The input line is too long.
The syntax of the command is incorrect.
ERROR: Build step failed with exception
ru.yandex.qatools.allure.jenkins.exception.AllurePluginException: Can not generate Allure Report, exit code: 255
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.generateReport(AllureReportPublisher.java:314)
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.perform(AllureReportPublisher.java:231)
	at jenkins.tasks.SimpleBuildStep.perform(SimpleBuildStep.java:123)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:78)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:806)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:755)
	at hudson.model.Build$BuildExecution.post2(Build.java:178)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:699)
	at hudson.model.Run.execute(Run.java:1913)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:99)
	at hudson.model.Executor.run(Executor.java:431)
Build step 'Allure Report' marked build as failure
Finished: FAILURE
```

Tried upgrading and downgrading the command line version but ran into the same issue above

**Comment by carlbray** [comment]
I noticed this issue on a Windows 2012 R2 Server with version allure-commandline-2.17.2.zip

I have a fix for this. Since Java 1.6 you can use wildcards in the classpath.

In the allure.bat file I changed the CLASSPATH to:
`set CLASSPATH=%APP_HOME%\lib\*;%APP_HOME%\lib\config`

I would submit a PR but I can't find the source for this file.

**Comment by renatahdo** [comment]
> I noticed this issue on a Windows 2012 R2 Server with version allure-commandline-2.17.2.zip
> 
> I have a fix for this. Since Java 1.6 you can use wildcards in the classpath.
> 
> In the allure.bat file I changed the CLASSPATH to: `set CLASSPATH=%APP_HOME%\lib\*;%APP_HOME%\lib\config`
> 
> I would submit a PR but I can't find the source for this file.

Great, man! This helped me a lot. Thank you so much!!!!!
