### ISSUE TITLE
XRAY Plugin -> Ignore all spaces when user picks several test executions

### ISSUE THREAD

**Issue by fedavar** [allure-framework/allure2#1508]
We use Jenkins to run the test and Xray plugin to update the test executions in Xray. Once we specify only one test execution by setting the property 
ALLURE_XRAY_EXECUTION_ISSUES=XXX-1234
everything goes perfectly. Report is generated, test runs are updated. 
But once we initialize the property like this
ALLURE_XRAY_EXECUTION_ISSUES=XXX-1234, XXX-1235
everything ruins - no allure report is generated after the build and no test runs are updated with corresponding statuses. This what we've got in Jenkins
```
Exception in thread "main" java.lang.NullPointerException
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at io.qameta.allure.xray.XrayTestRunExportPlugin.updateTestRunStatuses(XrayTestRunExportPlugin.java:107)
	at io.qameta.allure.xray.XrayTestRunExportPlugin.aggregate(XrayTestRunExportPlugin.java:96)
	at io.qameta.allure.ReportGenerator.aggregate(ReportGenerator.java:53)
	at io.qameta.allure.ReportGenerator.generate(ReportGenerator.java:70)
	at io.qameta.allure.ReportGenerator.generate(ReportGenerator.java:58)
	at io.qameta.allure.Commands.generate(Commands.java:104)
	at io.qameta.allure.CommandLine.run(CommandLine.java:152)
	at java.util.Optional.orElseGet(Optional.java:267)
	at io.qameta.allure.CommandLine.main(CommandLine.java:88)
ERROR: Build step failed with exception
ru.yandex.qatools.allure.jenkins.exception.AllurePluginException: Can not generate Allure Report, exit code: 1
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.generateReport(AllureReportPublisher.java:314)
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.perform(AllureReportPublisher.java:231)
	at jenkins.tasks.SimpleBuildStep.perform(SimpleBuildStep.java:123)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:80)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:803)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:752)
	at hudson.model.Build$BuildExecution.post2(Build.java:177)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:697)
	at hudson.model.Run.execute(Run.java:1931)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Build step 'Allure Report' marked build as failure
Collecting metadata...
Metadata collection done.
Finished: FAILURE
```
We found out that it works only when there are no spaces in comma separated string, like this
ALLURE_XRAY_EXECUTION_ISSUES=XXX-1234,XXX-1235,XXX-1236

There's a suggestion to add trim() to XrayTestRunExportPlugin.splitByComma(final String value) method. 

Sometimes anyone can add spaces befor/after the execution, for example during copy/paste. Plugin can handle such cases automatically removing the redundant spaces . In plugin documentation there is no exact info of how to use ALLURE_XRAY_EXECUTION_ISSUES property when you need to link test results to several executions so anyone else can face the issue we had.

**Comment by baev** [comment]
@fedavar could you please submit a PR with suggested change?

**Comment by fedavar** [comment]
Hello @baev ,
Thanks for quick response. I've made a quick fix for the current issue but later today we faced another issue. When Xray executions contain the same test runs (actually the same test cases but with unique test run id) and we try to export allure results to those executions we get this:
```Exception in thread "main" java.lang.IllegalStateException: Duplicate key XrayTestRun(id=xxxxxxx, key=XXX-1399, status=TODO)
	at java.util.stream.Collectors.lambda$throwingMerger$0(Collectors.java:133)
	at java.util.HashMap.merge(HashMap.java:1254)
	at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1320)
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at io.qameta.allure.xray.XrayTestRunExportPlugin.updateTestRunStatuses(XrayTestRunExportPlugin.java:107)
	at io.qameta.allure.xray.XrayTestRunExportPlugin.aggregate(XrayTestRunExportPlugin.java:96)
	at io.qameta.allure.ReportGenerator.aggregate(ReportGenerator.java:53)
	at io.qameta.allure.ReportGenerator.generate(ReportGenerator.java:70)
	at io.qameta.allure.ReportGenerator.generate(ReportGenerator.java:58)
	at io.qameta.allure.Commands.generate(Commands.java:104)
	at io.qameta.allure.CommandLine.run(CommandLine.java:152)
	at java.util.Optional.orElseGet(Optional.java:267)
	at io.qameta.allure.CommandLine.main(CommandLine.java:88)
ERROR: Build step failed with exception
ru.yandex.qatools.allure.jenkins.exception.AllurePluginException: Can not generate Allure Report, exit code: 1
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.generateReport(AllureReportPublisher.java:314)
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.perform(AllureReportPublisher.java:231)
	at jenkins.tasks.SimpleBuildStep.perform(SimpleBuildStep.java:123)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:80)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:803)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:752)
	at hudson.model.Build$BuildExecution.post2(Build.java:177)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:697)
	at hudson.model.Run.execute(Run.java:1931)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Build step 'Allure Report' marked build as failure
Collecting metadata...
Metadata collection done.
Finished: FAILURE
```
I found the root cause and implemented the solution in the same commit. Also added a test to check that everything works as expected. 
If you have any concerns about the second fix I can move it out. The fix of the initial issue with spaces in a comma separated string is just a one-line change.
