### ISSUE TITLE
Unrecognized field "testCaseName"

### ISSUE THREAD

**Issue by pandoras-toolbox** [allure-framework/allure2#1519]
Since Allure version 2.17.0 when I start the Gradle task "allureReport" this error is displayed:

```
> Task :bl-test:allureReport
Could not read test result file /Users/zeljko.markovic/IdeaProjects/syrius-productmgmt-automatedtesting/subprojects/bl-test/build/allure-results/a16955e8-f2b4-408f-985e-a435dfa32ee6-result.json
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "testCaseName" (class io.qameta.allure.model.TestResult), not marked as ignorable (18 known properties: "start", "descriptionHtml", "parameters", "name", "historyId", "statusDetails", "status", "links", "fullName", "uuid", "description", "testCaseId", "stage", "labels", "stop", "steps", "rerunOf", "attachments"])
 at [Source: (sun.nio.ch.ChannelInputStream); line: 1, column: 236] (through reference chain: io.qameta.allure.model.TestResult["testCaseName"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:823)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1153)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1589)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1567)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:294)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3070)
	at io.qameta.allure.allure2.Allure2Plugin.readTestResult(Allure2Plugin.java:344)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at io.qameta.allure.allure2.Allure2Plugin.readResults(Allure2Plugin.java:104)
	at io.qameta.allure.ReportGenerator.lambda$readResults$0(ReportGenerator.java:47)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at io.qameta.allure.ReportGenerator.readResults(ReportGenerator.java:47)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at io.qameta.allure.ReportGenerator.generate(ReportGenerator.java:69)
	at io.qameta.allure.ReportGenerator.generate(ReportGenerator.java:58)
	at io.qameta.allure.Commands.generate(Commands.java:104)
	at io.qameta.allure.CommandLine.run(CommandLine.java:152)
	at java.base/java.util.Optional.orElseGet(Optional.java:369)
	at io.qameta.allure.CommandLine.main(CommandLine.java:88)

```

I cannot tell you how to reproduce it because it happens in our closed-source code. Hopefully the stacktrace is enough and the content of the file a16955e8-f2b4-408f-985e-a435dfa32ee6-result.json below which I anonymized a bit.

Is it a bug? Or can I do something to avoid the error?

```
{
  "uuid": "a16955e8-f2b4-408f-985e-a435dfa32ee6",
  "historyId": "572ff30cad11e535510d319e19f28409",
  "testCaseId": "[engine:junit-jupiter]/[class:com.foobar.orion.blah.bl.v6beta1.AddSomethingTest]/[method:addSomething()]",
  "testCaseName": "addSomething()",
  "fullName": "com.foobar.orion.blah.bl.v6beta1.AddSomethingTest.addSomething",
  "labels": [
    {
      "name": "junit.platform.uniqueid",
      "value": "[engine:junit-jupiter]/[class:com.foobar.orion.blah.bl.v6beta1.AddSomethingTest]/[method:addSomething()]"
    },
    {
      "name": "epic",
      "value": "v6beta1"
    },
    {
      "name": "feature",
      "value": "AddService"
    },
    {
      "name": "host",
      "value": "ADC-MB10215"
    },
    {
      "name": "thread",
      "value": "7600@ADC-MB10215.ForkJoinPool-1-worker-3(26)"
    },
    {
      "name": "framework",
      "value": "junit-platform"
    },
    {
      "name": "language",
      "value": "java"
    },
    {
      "name": "package",
      "value": "com.foobar.orion.blah.bl.v6beta1.AddSomethingTest"
    },
    {
      "name": "testClass",
      "value": "com.foobar.orion.blah.bl.v6beta1.AddSomethingTest"
    },
    {
      "name": "testMethod",
      "value": "addSomething"
    },
    {
      "name": "suite",
      "value": "com.foobar.orion.blah.bl.v6beta1.AddSomethingTest"
    }
  ],
  "links": [
    {
      "name": "Graylog (Product Catalogue BL)",
      "url": "https://logging.com/search?q=ns_name%3Ateam-one+AND+pod_name%3Aorion-blah-bl-%2A&rangetype=relative&streams=603377c4a55d825acc34f289&from=86400"
    }
  ],
  "name": "addSomething()",
  "status": "passed",
  "stage": "finished",
  "description": "",
  "steps": [
    {
      "name": "sendRequest",
      "status": "passed",
      "stage": "finished",
      "steps": [],
      "attachments": [
        {
          "name": "addSomethingRequest",
          "source": "99330a5b-9915-4950-b2ea-a9b4861bb94c-attachment",
          "type": "text/json"
        },
        {
          "name": "addSomethingResponse",
          "source": "6a10b5e5-dbe1-44b5-8e09-0f9b853badd8-attachment",
          "type": "text/json"
        }
      ],
      "parameters": [],
      "start": 1639126789855,
      "stop": 1639126791988
    },
    {
      "name": "checkNoAlerts",
      "status": "passed",
      "stage": "finished",
      "steps": [
        {
          "name": "isEmpty",
          "status": "passed",
          "stage": "finished",
          "steps": [],
          "attachments": [],
          "parameters": [],
          "start": 1639126793654,
          "stop": 1639126793656
        }
      ],
      "attachments": [],
      "parameters": [
        {
          "name": "alerts",
          "value": "[]"
        }
      ],
      "start": 1639126792041,
      "stop": 1639126793656
    },
    {
      "name": "assertThat '23d1da18-ea1b-49ac-ae69-d131b17167b8'",
      "status": "passed",
      "stage": "finished",
      "steps": [],
      "attachments": [],
      "parameters": [],
      "start": 1639126793850,
      "stop": 1639126793851
    },
    {
      "name": "as 'Value at JSONPath: $.bundle.elements[0].id.value []'",
      "status": "passed",
      "stage": "finished",
      "steps": [
        {
          "name": "describedAs 'Value at JSONPath: $.bundle.elements[0].id.value'",
          "status": "passed",
          "stage": "finished",
          "steps": [],
          "attachments": [],
          "parameters": [],
          "start": 1639126793855,
          "stop": 1639126793856
        }
      ],
      "attachments": [],
      "parameters": [],
      "start": 1639126793855,
      "stop": 1639126793856
    },
    {
      "name": "isEqualTo '23d1da18-ea1b-49ac-ae69-d131b17167b8'",
      "status": "passed",
      "stage": "finished",
      "steps": [],
      "attachments": [],
      "parameters": [],
      "start": 1639126793856,
      "stop": 1639126793856
    },
    {
      "name": "assertThat 'STAT_CHANGE'",
      "status": "passed",
      "stage": "finished",
      "steps": [],
      "attachments": [],
      "parameters": [],
      "start": 1639126793874,
      "stop": 1639126793874
    },
    {
      "name": "as 'Value at JSONPath: $.bundle.change_status []'",
      "status": "passed",
      "stage": "finished",
      "steps": [
        {
          "name": "describedAs 'Value at JSONPath: $.bundle.change_status'",
          "status": "passed",
          "stage": "finished",
          "steps": [],
          "attachments": [],
          "parameters": [],
          "start": 1639126793874,
          "stop": 1639126793874
        }
      ],
      "attachments": [],
      "parameters": [],
      "start": 1639126793874,
      "stop": 1639126793874
    },
    {
      "name": "isEqualTo 'STAT_CHANGE'",
      "status": "passed",
      "stage": "finished",
      "steps": [],
      "attachments": [],
      "parameters": [],
      "start": 1639126793874,
      "stop": 1639126793874
    },
    {
      "name": "assertThat 'STATUS_ADD'",
      "status": "passed",
      "stage": "finished",
      "steps": [],
      "attachments": [],
      "parameters": [],
      "start": 1639126793884,
      "stop": 1639126793884
    },
    {
      "name": "as 'Value at JSONPath: $.bundle.elements[0].change_status []'",
      "status": "passed",
      "stage": "finished",
      "steps": [
        {
          "name": "describedAs 'Value at JSONPath: $.bundle.elements[0].change_status'",
          "status": "passed",
          "stage": "finished",
          "steps": [],
          "attachments": [],
          "parameters": [],
          "start": 1639126793885,
          "stop": 1639126793885
        }
      ],
      "attachments": [],
      "parameters": [],
      "start": 1639126793884,
      "stop": 1639126793885
    },
    {
      "name": "isEqualTo 'STATUS_ADD'",
      "status": "passed",
      "stage": "finished",
      "steps": [],
      "attachments": [],
      "parameters": [],
      "start": 1639126793885,
      "stop": 1639126793885
    },
    {
      "name": "assertThat 'STATUS_ADD'",
      "status": "passed",
      "stage": "finished",
      "steps": [],
      "attachments": [],
      "parameters": [],
      "start": 1639126793897,
      "stop": 1639126793897
    },
    {
      "name": "as 'Value at JSONPath: $.bundle.elements[0].something[0].change_status []'",
      "status": "passed",
      "stage": "finished",
      "steps": [
        {
          "name": "describedAs 'Value at JSONPath: $.bundle.elements[0].something[0].change_status'",
          "status": "passed",
          "stage": "finished",
          "steps": [],
          "attachments": [],
          "parameters": [],
          "start": 1639126793897,
          "stop": 1639126793897
        }
      ],
      "attachments": [],
      "parameters": [],
      "start": 1639126793897,
      "stop": 1639126793897
    },
    {
      "name": "isEqualTo 'STATUS_ADD'",
      "status": "passed",
      "stage": "finished",
      "steps": [],
      "attachments": [],
      "parameters": [],
      "start": 1639126793897,
      "stop": 1639126793897
    },
    {
      "name": "assertThat 'STATUS_ADD'",
      "status": "passed",
      "stage": "finished",
      "steps": [],
      "attachments": [],
      "parameters": [],
      "start": 1639126793903,
      "stop": 1639126793903
    },
    {
      "name": "as 'Value at JSONPath: $.bundle.elements[0].something[0].change_status []'",
      "status": "passed",
      "stage": "finished",
      "steps": [
        {
          "name": "describedAs 'Value at JSONPath: $.bundle.elements[0].something[0].change_status'",
          "status": "passed",
          "stage": "finished",
          "steps": [],
          "attachments": [],
          "parameters": [],
          "start": 1639126793903,
          "stop": 1639126793903
        }
      ],
      "attachments": [],
      "parameters": [],
      "start": 1639126793903,
      "stop": 1639126793903
    },
    {
      "name": "isEqualTo 'STATUS_ADD'",
      "status": "passed",
      "stage": "finished",
      "steps": [],
      "attachments": [],
      "parameters": [],
      "start": 1639126793903,
      "stop": 1639126793904
    },
    {
      "name": "assertThat 'STATUS_ADD'",
      "status": "passed",
      "stage": "finished",
      "steps": [],
      "attachments": [],
      "parameters": [],
      "start": 1639126793910,
      "stop": 1639126793910
    },
    {
      "name": "as 'Value at JSONPath: $.bundle.elements[0].something[0].insured_object_type_group[0].motor_vehicles.motor_vehicle[0].insured_object.change_status []'",
      "status": "passed",
      "stage": "finished",
      "steps": [
        {
          "name": "describedAs 'Value at JSONPath: $.bundle.elements[0].something[0].insured_object_type_group[0].motor_vehicles.motor_vehicle[0].insured_object.change_status'",
          "status": "passed",
          "stage": "finished",
          "steps": [],
          "attachments": [],
          "parameters": [],
          "start": 1639126793910,
          "stop": 1639126793910
        }
      ],
      "attachments": [],
      "parameters": [],
      "start": 1639126793910,
      "stop": 1639126793910
    },
    {
      "name": "isEqualTo 'STATUS_ADD'",
      "status": "passed",
      "stage": "finished",
      "steps": [],
      "attachments": [],
      "parameters": [],
      "start": 1639126793910,
      "stop": 1639126793910
    },
    {
      "name": "assertThat 'STATUS_ADD'",
      "status": "passed",
      "stage": "finished",
      "steps": [],
      "attachments": [],
      "parameters": [],
      "start": 1639126793917,
      "stop": 1639126793917
    },
    {
      "name": "as 'Value at JSONPath: $.bundle.elements[0].something[0].house[0].change_status []'",
      "status": "passed",
      "stage": "finished",
      "steps": [
        {
          "name": "describedAs 'Value at JSONPath: $.bundle.elements[0].something[0].house[0].change_status'",
          "status": "passed",
          "stage": "finished",
          "steps": [],
          "attachments": [],
          "parameters": [],
          "start": 1639126793918,
          "stop": 1639126793918
        }
      ],
      "attachments": [],
      "parameters": [],
      "start": 1639126793917,
      "stop": 1639126793918
    },
    {
      "name": "isEqualTo 'STATUS_ADD'",
      "status": "passed",
      "stage": "finished",
      "steps": [],
      "attachments": [],
      "parameters": [],
      "start": 1639126793918,
      "stop": 1639126793918
    },
    {
      "name": "assertThat 'STATUS_ADD'",
      "status": "passed",
      "stage": "finished",
      "steps": [],
      "attachments": [],
      "parameters": [],
      "start": 1639126793924,
      "stop": 1639126793924
    },
    {
      "name": "as 'Value at JSONPath: $.bundle.elements[0].something[0].house[0].props[0].information.change_status []'",
      "status": "passed",
      "stage": "finished",
      "steps": [
        {
          "name": "describedAs 'Value at JSONPath: $.bundle.elements[0].something[0].house[0].props[0].information.change_status'",
          "status": "passed",
          "stage": "finished",
          "steps": [],
          "attachments": [],
          "parameters": [],
          "start": 1639126793925,
          "stop": 1639126793925
        }
      ],
      "attachments": [],
      "parameters": [],
      "start": 1639126793924,
      "stop": 1639126793925
    },
    {
      "name": "isEqualTo 'STATUS_ADD'",
      "status": "passed",
      "stage": "finished",
      "steps": [],
      "attachments": [],
      "parameters": [],
      "start": 1639126793925,
      "stop": 1639126793925
    },
    {
      "name": "assertThat 'STATUS_ADD'",
      "status": "passed",
      "stage": "finished",
      "steps": [],
      "attachments": [],
      "parameters": [],
      "start": 1639126793931,
      "stop": 1639126793931
    },
    {
      "name": "as 'Value at JSONPath: $.bundle.elements[0].something[0].house[0].blubb[0].change_status []'",
      "status": "passed",
      "stage": "finished",
      "steps": [
        {
          "name": "describedAs 'Value at JSONPath: $.bundle.elements[0].something[0].house[0].blubb[0].change_status'",
          "status": "passed",
          "stage": "finished",
          "steps": [],
          "attachments": [],
          "parameters": [],
          "start": 1639126793931,
          "stop": 1639126793931
        }
      ],
      "attachments": [],
      "parameters": [],
      "start": 1639126793931,
      "stop": 1639126793931
    },
    {
      "name": "isEqualTo 'STATUS_ADD'",
      "status": "passed",
      "stage": "finished",
      "steps": [],
      "attachments": [],
      "parameters": [],
      "start": 1639126793931,
      "stop": 1639126793931
    },
    {
      "name": "assertThat '20'",
      "status": "passed",
      "stage": "finished",
      "steps": [],
      "attachments": [],
      "parameters": [],
      "start": 1639126793932,
      "stop": 1639126793932
    },
    {
      "name": "as 'sortKey []'",
      "status": "passed",
      "stage": "finished",
      "steps": [
        {
          "name": "describedAs 'sortKey'",
          "status": "passed",
          "stage": "finished",
          "steps": [],
          "attachments": [],
          "parameters": [],
          "start": 1639126793933,
          "stop": 1639126793933
        }
      ],
      "attachments": [],
      "parameters": [],
      "start": 1639126793932,
      "stop": 1639126793933
    },
    {
      "name": "isEqualTo '20'",
      "status": "passed",
      "stage": "finished",
      "steps": [],
      "attachments": [],
      "parameters": [],
      "start": 1639126793933,
      "stop": 1639126793933
    },
    {
      "name": "as 'specialOrigin []'",
      "status": "passed",
      "stage": "finished",
      "steps": [
        {
          "name": "describedAs 'specialOrigin'",
          "status": "passed",
          "stage": "finished",
          "steps": [],
          "attachments": [],
          "parameters": [],
          "start": 1639126793933,
          "stop": 1639126793933
        }
      ],
      "attachments": [],
      "parameters": [],
      "start": 1639126793933,
      "stop": 1639126793933
    },
    {
      "name": "isEqualTo 'CASE_EMPTY'",
      "status": "passed",
      "stage": "finished",
      "steps": [],
      "attachments": [],
      "parameters": [],
      "start": 1639126793933,
      "stop": 1639126793933
    },
    {
      "name": "assertThat '10'",
      "status": "passed",
      "stage": "finished",
      "steps": [],
      "attachments": [],
      "parameters": [],
      "start": 1639126793934,
      "stop": 1639126793934
    },
    {
      "name": "as 'sortKey []'",
      "status": "passed",
      "stage": "finished",
      "steps": [
        {
          "name": "describedAs 'sortKey'",
          "status": "passed",
          "stage": "finished",
          "steps": [],
          "attachments": [],
          "parameters": [],
          "start": 1639126793934,
          "stop": 1639126793934
        }
      ],
      "attachments": [],
      "parameters": [],
      "start": 1639126793934,
      "stop": 1639126793934
    },
    {
      "name": "isEqualTo '10'",
      "status": "passed",
      "stage": "finished",
      "steps": [],
      "attachments": [],
      "parameters": [],
      "start": 1639126793934,
      "stop": 1639126793934
    },
    {
      "name": "assertThat 'Some_Value'",
      "status": "passed",
      "stage": "finished",
      "steps": [],
      "attachments": [],
      "parameters": [],
      "start": 1639126793934,
      "stop": 1639126793934
    },
    {
      "name": "describedAs 'value'",
      "status": "passed",
      "stage": "finished",
      "steps": [],
      "attachments": [],
      "parameters": [],
      "start": 1639126793934,
      "stop": 1639126793934
    },
    {
      "name": "isEqualTo 'Some_Value'",
      "status": "passed",
      "stage": "finished",
      "steps": [
        {
          "name": "isEqualTo 'Some_Value'",
          "status": "passed",
          "stage": "finished",
          "steps": [],
          "attachments": [],
          "parameters": [],
          "start": 1639126793935,
          "stop": 1639126793935
        }
      ],
      "attachments": [],
      "parameters": [],
      "start": 1639126793934,
      "stop": 1639126793935
    },
    {
      "name": "as 'type []'",
      "status": "passed",
      "stage": "finished",
      "steps": [
        {
          "name": "describedAs 'type'",
          "status": "passed",
          "stage": "finished",
          "steps": [],
          "attachments": [],
          "parameters": [],
          "start": 1639126793935,
          "stop": 1639126793935
        }
      ],
      "attachments": [],
      "parameters": [],
      "start": 1639126793935,
      "stop": 1639126793935
    },
    {
      "name": "isEqualTo 'KEY_DYNAMIC'",
      "status": "passed",
      "stage": "finished",
      "steps": [],
      "attachments": [],
      "parameters": [],
      "start": 1639126793935,
      "stop": 1639126793935
    }
  ],
  "attachments": [],
  "parameters": [],
  "start": 1639126788309,
  "stop": 1639126793936
}
```

**Comment by baev** [comment]
what version of allure report are you using? Report generator itself should be the same or higher version

**Comment by pandoras-toolbox** [comment]
The Allure version is a constant in our project which I reference in Gradle for all of the Allure dependencies. Up to version 2.16.1 it works with report generation. For the Gradle plugin I use Allure version 2.9.6.

**Comment by baev** [comment]
https://github.com/allure-framework/allure-gradle#configuring-allure-version

**Comment by pandoras-toolbox** [comment]
Thank you, it worked, but I needed to set it like this:
```
allure {
  version.set("2.17.1")
```
