### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by NatalyaAlferina** [allure-framework/allure2#1942]
**Describe the bug**
I'm install extension for vscode and try invoking AllureTestOps upload test results after getting in log follow:
``` sh
FetchError: invalid json response body at https:/... /api/rs/launch/upload reason: Unexpected end of JSON input
    at /.vscode-server/extensions/qameta.allure-vscode-1.0.6/out/extension.js:2003:40
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async postProxy (.vscode-server/extensions/qameta.allure-vscode-1.0.6/out/extension.js:27520:16)
    at async post (/.vscode-server/extensions/qameta.allure-vscode-1.0.6/out/extension.js:27538:16)
    at async upload (/.vscode-server/extensions/qameta.allure-vscode-1.0.6/out/extension.js:27685:15)
    at async uploadResultsCmd (/.vscode-server/extensions/qameta.allure-vscode-1.0.6/out/extension.js:27739:23)
    at async c.h (/.vscode-server/bin/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:96:108776)
```

**To Reproduce**
1. Go to 'context menu'
2. Click on 'AllureTestOps upload test results'

**Environment (please complete the following information):**

| Allure version | 2.21.0 |

**Comment by cheshi-mantu** [comment]
@NatalyaAlferina hi Natalya
accordingly to the community rules, all the issues must be submitted in English only.
Please rewrite your issue as per the community rules.

**Comment by zhivanshe** [comment]
Error on the user side.
> The extension sends test results directory as is, so it shouldn't be changed since it was generated by reporter.

I close it until I receive a response from the user
