### ISSUE TITLE
Error: Unauthorized

### ISSUE THREAD

**Issue by NatalyaAlferina** [allure-framework/allure2#1945]
**Describe the bug**
I'm install extension for vscode and try invoking `Allure TestOps: test connection` log follow:

**To Reproduce**
1. Go to 'ctrl P'
2. Click on 'Allure TestOps: test connection'
```
Error: Unauthorized
  at getProxy (/.vscode-server/extensions/qameta.allure-vscode-1.0.6/out/extension.js:27507:11)
  at runMicrotasks (<anonymous>)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async get (/.vscode-server/extensions/qameta.allure-vscode-1.0.6/out/extension.js:27529:16)
  at async testConnectionCmd (/.vscode-server/extensions/qameta.allure-vscode-1.0.6/out/extension.js:27659:5)
  at async c.h (/.vscode-server/bin/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:96:108776)
```

| Allure version | 2.21.0 |

**Comment by NatalyaAlferina** [comment]
Solution is download allurectl
```
❯ ./allurectl auth login --endpoint --token 
Successfully authorized as user ...
```
