### ISSUE TITLE
on jenkins looking for file testrun.json; it doesnt exists

### ISSUE THREAD

**Issue by turnitin-rshanker** [allure-framework/allure2#2073]
### Describe the Bug

on jenkins looking for file testrun.json; it doesnt exists.  causing jenkins build to fail even there is no test failure
java.nio.file.AccessDeniedException: ../../../../testrun.json

note: not using Allure Report plugin/integration

### Steps to Reproduce

open jenkins job and run tests
you will see jenkins job failed

### Expected Behaviour

expected to have allure to created testrun.json file

### What Language are you using?

Java

### What Framework/Allure Integration you are using?

allure-testng

### What version of Allure Integration you are using?

2.23.0

### What version of Allure Report you are using?

0.0.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by turnitin-rshanker** [comment]
one more thing, I dont see that file even in the local run

**Comment by cheshi-mantu** [comment]
@turnitin-rshanker could you please add jenkins' console log for the failed build as txt file?

**Comment by turnitin-rshanker** [comment]
```11:15:55  [INFO] Results:
11:15:55  [INFO] 
11:15:55  [INFO] Tests run: 24, Failures: 0, Errors: 0, Skipped: 0
11:15:55  [INFO] 
11:15:55  [INFO] ------------------------------------------------------------------------
11:15:55  [INFO] BUILD SUCCESS
11:15:55  [INFO] ------------------------------------------------------------------------
11:15:55  [INFO] Total time:  39.150 s
11:15:55  [INFO] Finished at: 2023-08-08T18:15:55Z
11:15:55  [INFO] ------------------------------------------------------------------------
11:15:55  [WARNING] 
11:15:55  [WARNING] Plugin validation issues were detected in 3 plugin(s)
11:15:55  [WARNING] 
11:15:55  [WARNING]  * org.apache.maven.plugins:maven-compiler-plugin:3.8.1
11:15:55  [WARNING]  * org.apache.maven.plugins:maven-surefire-plugin:3.1.2
11:15:55  [WARNING]  * org.apache.maven.plugins:maven-resources-plugin:3.3.0
11:15:55  [WARNING] 
11:15:55  [WARNING] For more or less details, use 'maven.plugin.validation' property with one of the values (case insensitive): [BRIEF, DEFAULT, VERBOSE]
11:15:55  [WARNING] 
11:15:55  run-tests returned 0
11:15:55  Jenkins workspace detected, create directories for storing test artifacts...
11:15:56  run-tests: ...copied JUnit reports to /home/jenkins/agent/workspace/Redwood QA/boilerplate-java-selenium/validate/junit/
11:15:56  ...copied logs to Jenkins workspace @ '/home/jenkins/agent/workspace/Redwood QA/boilerplate-java-selenium/validate/logs/'
11:15:56  total 352
11:15:56  drwxr-xr-x 2 root root 8192 Aug  8 18:15 .
11:15:56  drwxr-xr-x 8 root root  134 Aug  8 18:15 ..
11:15:56  -rw-r--r-- 1 root root  418 Aug  8 18:15 004b0f56-9552-4002-b033-074fa728b5cd-container.json
11:15:56  -rw-r--r-- 1 root root  418 Aug  8 18:15 01f1899c-df8e-4ad6-a672-9842f2a5fec3-container.json
11:15:56  -rw-r--r-- 1 root root  386 Aug  8 18:15 0451578d-15e7-4587-b4e3-689d25750ae1-container.json
11:15:56  -rw-r--r-- 1 root root  348 Aug  8 18:15 0475c5e5-5768-4e9f-ba5f-9c6e952e1521-container.json
11:15:56  -rw-r--r-- 1 root root  386 Aug  8 18:15 0aa380a8-52ae-483d-9508-ad0457ce8b6b-container.json
11:15:56  -rw-r--r-- 1 root root  386 Aug  8 18:15 10e8b3bd-8f01-4016-862c-cc2c18e6f135-container.json
11:15:56  -rw-r--r-- 1 root root  243 Aug  8 18:15 110be2d9-832f-4973-a892-2d9e1a8f99ff-container.json
11:15:56  -rw-r--r-- 1 root root 1091 Aug  8 18:15 131df143-d51a-4a09-ba4f-fa95225fcb44-result.json
11:15:56  -rw-r--r-- 1 root root  619 Aug  8 18:15 13e72fb3-6ba9-45a6-a47c-d7db2a484439-container.json
11:15:56  -rw-r--r-- 1 root root 1002 Aug  8 18:15 13ed3ae5-3cd0-4e42-8dbb-e7e77b9b3da4-result.json
11:15:56  -rw-r--r-- 1 root root  386 Aug  8 18:15 15391f8a-fdd1-4828-9f91-d84fe00301d9-container.json
11:15:56  -rw-r--r-- 1 root root  418 Aug  8 18:15 158b8f18-f389-4a23-a2d3-44a0f5bcf9a2-container.json
11:15:56  -rw-r--r-- 1 root root  386 Aug  8 18:15 1893bff2-86a4-476a-971a-8921375150cd-container.json
11:15:56  -rw-r--r-- 1 root root  386 Aug  8 18:15 1ca44623-dbce-4c24-b01f-896946e88302-container.json
11:15:56  -rw-r--r-- 1 root root  418 Aug  8 18:15 221b4380-c65e-4365-bc53-f66e8a0cd495-container.json
11:15:56  -rw-r--r-- 1 root root 1091 Aug  8 18:15 22771ea9-00de-4dcb-83dd-da9a41630ff9-result.json
11:15:56  -rw-r--r-- 1 root root  418 Aug  8 18:15 2487d9da-dffd-4aea-b73d-cee51ddd7cad-container.json
11:15:56  -rw-r--r-- 1 root root  418 Aug  8 18:15 24d4a4af-4034-4c24-8e35-8a6ebafdc0d7-container.json
11:15:56  -rw-r--r-- 1 root root  346 Aug  8 18:15 285f1a2b-f781-4b5d-908d-74982c1ec880-container.json
11:15:56  -rw-r--r-- 1 root root  386 Aug  8 18:15 29adbc65-817d-4051-8f30-b2eeed16a705-container.json
11:15:56  -rw-r--r-- 1 root root  951 Aug  8 18:15 2b7f7a20-c868-47f4-9d7f-a14a2f60a0e4-result.json
11:15:56  -rw-r--r-- 1 root root  418 Aug  8 18:15 2d8df602-e7d0-406e-9f8e-8d3def6a874f-container.json
11:15:56  -rw-r--r-- 1 root root  386 Aug  8 18:15 2fcd4bfd-87c1-45b4-98a7-7e7055295a47-container.json
11:15:56  -rw-r--r-- 1 root root  386 Aug  8 18:15 30544ae8-a34b-4eb2-9c1d-3d31defb4ef7-container.json
11:15:56  -rw-r--r-- 1 root root  418 Aug  8 18:15 329b8a2a-0d9a-469a-be6f-56e0237f4b1d-container.json
11:15:56  -rw-r--r-- 1 root root  978 Aug  8 18:15 345d8d65-a6f8-47b6-8ff4-5b0c2af27cfa-result.json
11:15:56  -rw-r--r-- 1 root root  418 Aug  8 18:15 38ae5dfd-dbcd-4384-84c5-8091d9be437b-container.json
11:15:56  -rw-r--r-- 1 root root  386 Aug  8 18:15 39a7a961-6d87-4b88-9743-c89a3cda3e93-container.json
11:15:56  -rw-r--r-- 1 root root  418 Aug  8 18:15 3c0d192d-394a-44ba-9431-0b51ae4e3f4c-container.json
11:15:56  -rw-r--r-- 1 root root  386 Aug  8 18:15 414cfd0b-07cc-4a13-8207-5777d73ee5b3-container.json
11:15:56  -rw-r--r-- 1 root root  418 Aug  8 18:15 4a00190b-405f-47d8-8a0f-fc6e37620580-container.json
11:15:56  -rw-r--r-- 1 root root 1008 Aug  8 18:15 4b98ab3e-4fce-474a-8014-b036ec022c64-result.json
11:15:56  -rw-r--r-- 1 root root  386 Aug  8 18:15 4e83e003-ab63-4c87-aa22-c31394d66266-container.json
11:15:56  -rw-r--r-- 1 root root  369 Aug  8 18:15 53ddf1b3-89d3-4807-92b9-ae0ac346bfdb-container.json
11:15:56  -rw-r--r-- 1 root root  975 Aug  8 18:15 5604afc9-de8e-4f65-a06d-0f2c8d74d890-result.json
11:15:56  -rw-r--r-- 1 root root  418 Aug  8 18:15 562163cb-4ed1-4bd6-8459-6498beb30feb-container.json
11:15:56  -rw-r--r-- 1 root root  418 Aug  8 18:15 5a66695e-ce86-492e-a045-f3aa321882fd-container.json
11:15:56  -rw-r--r-- 1 root root  386 Aug  8 18:15 5a6e805a-7c49-49c3-94e6-19340d0b0a90-container.json
11:15:56  -rw-r--r-- 1 root root  229 Aug  8 18:15 5bd0a2fe-d6a6-45ea-8bc4-3ea144ab142c-container.json
11:15:56  -rw-r--r-- 1 root root 1133 Aug  8 18:15 647a7a23-f52d-4a03-8d6a-37c6befb3ca8-result.json
11:15:56  -rw-r--r-- 1 root root  418 Aug  8 18:15 6f199b90-8f93-4a2d-a6f1-51f833f3a558-container.json
11:15:56  -rw-r--r-- 1 root root 1091 Aug  8 18:15 72de380a-7594-423c-b55c-1c8c80aae0d8-result.json
11:15:56  -rw-r--r-- 1 root root 1133 Aug  8 18:15 7896fe93-4904-420a-acb7-841d1ca80b7e-result.json
11:15:56  -rw-r--r-- 1 root root 1091 Aug  8 18:15 7a33ceb0-7431-47d4-b6b3-f26a1ce61ce4-result.json
11:15:56  -rw-r--r-- 1 root root  386 Aug  8 18:15 7a9af7bd-f836-4b68-a37b-7aafaeba1739-container.json
11:15:56  -rw-r--r-- 1 root root  418 Aug  8 18:15 7f92957c-a87a-4a97-8e8f-4246f644283f-container.json
11:15:56  -rw-r--r-- 1 root root  418 Aug  8 18:15 813072d1-ce22-40c6-8c4f-3ae0746348bb-container.json
11:15:56  -rw-r--r-- 1 root root  348 Aug  8 18:15 82e49b8e-1a70-41fb-a28f-4a7824358f49-container.json
11:15:56  -rw-r--r-- 1 root root  964 Aug  8 18:15 844b606e-131b-4e66-a766-0cffe50f7321-result.json
11:15:56  -rw-r--r-- 1 root root  386 Aug  8 18:15 866b0c19-68a5-4e97-aa8e-160fbe1af062-container.json
11:15:56  -rw-r--r-- 1 root root  386 Aug  8 18:15 86eafbe7-d245-416f-9821-84cadf791f9a-container.json
11:15:56  -rw-r--r-- 1 root root  418 Aug  8 18:15 878fbd65-2e57-43c7-bae6-9fcd01855493-container.json
11:15:56  -rw-r--r-- 1 root root  367 Aug  8 18:15 8c07a5fb-b2b5-468a-a61f-8373c8496d79-container.json
11:15:56  -rw-r--r-- 1 root root  418 Aug  8 18:15 95c036bc-e021-442b-98ba-6a8982cd8ee7-container.json
11:15:56  -rw-r--r-- 1 root root 1002 Aug  8 18:15 9a629a0c-e2fa-410f-9d25-81d96bad5651-result.json
11:15:56  -rw-r--r-- 1 root root  418 Aug  8 18:15 9c005397-6726-49e4-88b6-d423eb945f04-container.json
11:15:56  -rw-r--r-- 1 root root  386 Aug  8 18:15 9d7226cd-6fc5-418c-96d9-1ff128c41290-container.json
11:15:56  -rw-r--r-- 1 root root  386 Aug  8 18:15 a59512fa-755d-4082-822f-64229558f096-container.json
11:15:56  -rw-r--r-- 1 root root  386 Aug  8 18:15 ab2a5d0b-81ee-4ad3-b2f4-460c8a9ea217-container.json
11:15:56  -rw-r--r-- 1 root root 1133 Aug  8 18:15 b64c3ded-2b87-4d4d-80b2-fd1e93fb9c8d-result.json
11:15:56  -rw-r--r-- 1 root root 1133 Aug  8 18:15 b8c5ef34-52a7-49a0-965c-3f2b5cdbf28a-result.json
11:15:56  -rw-r--r-- 1 root root 1011 Aug  8 18:15 bbabb2b4-ca71-4ff9-a6fa-6e320a08bade-result.json
11:15:56  -rw-r--r-- 1 root root  418 Aug  8 18:15 bcc88b35-8341-40e7-9d47-ca5122719694-container.json
11:15:56  -rw-r--r-- 1 root root  418 Aug  8 18:15 be3227a4-ec77-48ee-80eb-e8485f00a900-container.json
11:15:56  -rw-r--r-- 1 root root  418 Aug  8 18:15 be3e0ae2-222f-4dfa-88ad-c6f8464b0514-container.json
11:15:56  -rw-r--r-- 1 root root 1133 Aug  8 18:15 c345a124-d1f0-47aa-933e-9f5302faecf9-result.json
11:15:56  -rw-r--r-- 1 root root  958 Aug  8 18:15 c53067de-db6e-4818-9b52-af542176e0ab-result.json
11:15:56  -rw-r--r-- 1 root root  386 Aug  8 18:15 c6f3c67f-631b-4e96-9fd0-4e4e5ffe6083-container.json
11:15:56  -rw-r--r-- 1 root root  637 Aug  8 18:15 c848f26e-dbc7-443a-b85e-9f5bafc41fb1-container.json
11:15:56  -rw-r--r-- 1 root root  386 Aug  8 18:15 ca4f1713-5929-4a4f-80c8-d029bc624818-container.json
11:15:56  -rw-r--r-- 1 root root 1008 Aug  8 18:15 cd4b9058-3218-46ae-9ae1-0e28d24e42f0-result.json
11:15:56  -rw-r--r-- 1 root root  418 Aug  8 18:15 cd67c921-8bea-434f-a533-578acdc46221-container.json
11:15:56  -rw-r--r-- 1 root root 1029 Aug  8 18:15 cec9ed0d-8bed-4de0-bac2-7d4066a11694-result.json
11:15:56  -rw-r--r-- 1 root root  386 Aug  8 18:15 d2cad25c-97ec-4421-a310-feeb5a11271b-container.json
11:15:56  -rw-r--r-- 1 root root 1091 Aug  8 18:15 d44cb300-ca34-472c-9fc6-c4b0d74a222c-result.json
11:15:56  -rw-r--r-- 1 root root  939 Aug  8 18:15 d5f65c96-768c-43a0-b189-71204bdf03c9-result.json
11:15:56  -rw-r--r-- 1 root root  386 Aug  8 18:15 dc2ad5b6-fc16-4f1b-9b0a-6e24c4a58016-container.json
11:15:56  -rw-r--r-- 1 root root  348 Aug  8 18:15 e92673aa-1ce6-4ca2-83a5-f194835970e4-container.json
11:15:56  -rw-r--r-- 1 root root  346 Aug  8 18:15 ed525b29-1c04-4c8c-8f2d-31c915fe3943-container.json
11:15:56  -rw-r--r-- 1 root root  207 Aug  8 18:15 environment.xml
11:15:56  -rw-r--r-- 1 root root  386 Aug  8 18:15 f13a1d8c-f17d-46fb-a4d3-f076f2860b2f-container.json
11:15:56  -rw-r--r-- 1 root root  975 Aug  8 18:15 f610c77c-1c2f-405a-8324-ff13e2140ad5-result.json
11:15:56  -rw-r--r-- 1 root root  418 Aug  8 18:15 f83b6850-d13c-4bda-9dc9-20d227a7837c-container.json
11:15:56  -rw-r--r-- 1 root root 1011 Aug  8 18:15 fb79fda6-e493-47ed-90d9-6c0cfe081dfd-result.json
11:15:56  -rw-r--r-- 1 root root  348 Aug  8 18:15 fce06f8b-0f2e-44ca-ba85-df03ee3eb4fc-container.json
11:15:56  ...copied allure output to allure-results/ in Jenkins workspace
11:15:56  [Pipeline] }
11:15:56  [Pipeline] // container
11:15:56  [Pipeline] }
11:15:56  [Pipeline] // stage
11:15:56  [Pipeline] stage
11:15:56  [Pipeline] { (Optionally deploy additional production envs)
11:15:56  Stage "Optionally deploy additional production envs" skipped due to when conditional
11:15:56  [Pipeline] }
11:15:56  [Pipeline] // stage
11:15:56  [Pipeline] stage
11:15:56  [Pipeline] { (Declarative: Post Actions)
11:15:57  [Pipeline] echo
11:15:57  Glob found in junitPath of 'junit/*.xml', calling findFiles...
11:15:57  [Pipeline] findFiles
11:15:57  [Pipeline] echo
11:15:57  findFiles matched 4 files
11:15:57  [Pipeline] junit
11:15:57  Recording test results
11:15:57  [Checks API] No suitable checks publisher found.
11:15:57  [Pipeline] findFiles
11:15:57  [Pipeline] archiveArtifacts
11:15:57  Archiving artifacts
11:15:57  [Pipeline] findFiles
11:15:57  [Pipeline] archiveArtifacts
11:15:57  Archiving artifacts
11:15:58  [Pipeline] findFiles
11:15:58  [Pipeline] archiveArtifacts
11:15:58  Archiving artifacts
11:15:59  [Pipeline] script
11:15:59  [Pipeline] {
11:15:59  [Pipeline] allure
11:15:59  [Pipeline] }
11:15:59  [Pipeline] // script
11:15:59  Error when executing always post condition:
11:15:59  Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from 172.28.114.80/172.28.114.80:59174
11:15:59  		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1784)
11:15:59  		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
11:15:59  		at hudson.remoting.Channel.call(Channel.java:1000)
11:15:59  		at hudson.FilePath.act(FilePath.java:1192)
11:15:59  		at hudson.FilePath.act(FilePath.java:1181)
11:15:59  		at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.addTestRunInfo(AllureReportPublisher.java:399)
11:15:59  		at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.prepareResults(AllureReportPublisher.java:390)
11:15:59  		at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.perform(AllureReportPublisher.java:230)
11:15:59  		at jenkins.tasks.SimpleBuildStep.perform(SimpleBuildStep.java:123)
11:15:59  		at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:101)
11:15:59  		at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:71)
11:15:59  		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
11:15:59  		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
11:15:59  		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
11:15:59  		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
11:15:59  		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
11:15:59  		at java.base/java.lang.Thread.run(Thread.java:829)
11:15:59  Also:   org.jenkinsci.plugins.workflow.actions.ErrorAction$ErrorId: 057e9493-8dd3-4ae4-be69-9828ab79c378
11:15:59  java.nio.file.AccessDeniedException: /home/jenkins/agent/workspace/Redwood QA/boilerplate-java-selenium/validate/allure-results/testrun.json
11:15:59  	at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)
11:15:59  	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
11:15:59  	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
11:15:59  	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(Unknown Source)
11:15:59  	at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(Unknown Source)
11:15:59  	at java.base/java.nio.file.Files.newOutputStream(Unknown Source)
11:15:59  	at java.base/java.nio.file.Files.newBufferedWriter(Unknown Source)
11:15:59  	at ru.yandex.qatools.allure.jenkins.callables.AbstractAddInfo.invoke(AbstractAddInfo.java:26)
11:15:59  	at ru.yandex.qatools.allure.jenkins.callables.AbstractAddInfo.invoke(AbstractAddInfo.java:19)
11:15:59  	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:3578)
11:15:59  	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
11:15:59  	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
11:15:59  	at hudson.remoting.Request$2.run(Request.java:377)
11:15:59  	at hudson.remoting.InterceptingExecutorService.lambda$wrap$0(InterceptingExecutorService.java:78)
11:15:59  	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
11:15:59  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
11:15:59  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
11:15:59  	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:125)
11:15:59  	at java.base/java.lang.Thread.run(Unknown Source)
11:15:59  
11:15:59  [Pipeline] echo
11:15:59  Refusing to invoke opsgenie: no 'teams' parameter.
11:15:59  [Pipeline] }
11:16:00  [Pipeline] // stage
11:16:00  [Pipeline] }
11:16:00  [Pipeline] // node
11:16:00  [Pipeline] }
11:16:00  [Pipeline] // podTemplate
11:16:00  [Pipeline] End of Pipeline
11:16:00  Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from 172.28.114.80/172.28.114.80:59174
11:16:00  		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1784)
11:16:00  		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
11:16:00  		at hudson.remoting.Channel.call(Channel.java:1000)
11:16:00  		at hudson.FilePath.act(FilePath.java:1192)
11:16:00  		at hudson.FilePath.act(FilePath.java:1181)
11:16:00  		at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.addTestRunInfo(AllureReportPublisher.java:399)
11:16:00  		at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.prepareResults(AllureReportPublisher.java:390)
11:16:00  		at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.perform(AllureReportPublisher.java:230)
11:16:00  		at jenkins.tasks.SimpleBuildStep.perform(SimpleBuildStep.java:123)
11:16:00  		at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:101)
11:16:00  		at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:71)
11:16:00  		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
11:16:00  		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
11:16:00  		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
11:16:00  		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
11:16:00  		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
11:16:00  		at java.base/java.lang.Thread.run(Thread.java:829)
11:16:00  Also:   org.jenkinsci.plugins.workflow.actions.ErrorAction$ErrorId: 057e9493-8dd3-4ae4-be69-9828ab79c378
11:16:00  java.nio.file.AccessDeniedException: /home/jenkins/agent/workspace/Redwood QA/boilerplate-java-selenium/validate/allure-results/testrun.json
11:16:00  	at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)
11:16:00  	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
11:16:00  	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
11:16:00  	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(Unknown Source)
11:16:00  	at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(Unknown Source)
11:16:00  	at java.base/java.nio.file.Files.newOutputStream(Unknown Source)
11:16:00  	at java.base/java.nio.file.Files.newBufferedWriter(Unknown Source)
11:16:00  	at ru.yandex.qatools.allure.jenkins.callables.AbstractAddInfo.invoke(AbstractAddInfo.java:26)
11:16:00  	at ru.yandex.qatools.allure.jenkins.callables.AbstractAddInfo.invoke(AbstractAddInfo.java:19)
11:16:00  	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:3578)
11:16:00  	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
11:16:00  	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
11:16:00  	at hudson.remoting.Request$2.run(Request.java:377)
11:16:00  	at hudson.remoting.InterceptingExecutorService.lambda$wrap$0(InterceptingExecutorService.java:78)
11:16:00  	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
11:16:00  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
11:16:00  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
11:16:00  	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:125)
11:16:00  	at java.base/java.lang.Thread.run(Unknown Source)
11:16:00  Finished: FAILURE
SCM Sync status :

**Comment by turnitin-rshanker** [comment]
@cheshi-mantu any update?

**Comment by baev** [comment]
Sorry for the delay. Please use the [Allure TestOps support portal](https://help.qameta.io/)
