### ISSUE TITLE
Something went wrong with Allure Report generation. Here are some details: java.lang.RuntimeException: Failed to generate allure report

### ISSUE THREAD

**Issue by diva1422** [allure-framework/allure2#2091]
### Describe the Bug

Something went wrong with Allure Report generation. Here are some details: 
java.lang.RuntimeException: Failed to generate allure report
	at io.qameta.allure.bamboo.AllureExecutable.generate(AllureExecutable.java:40)
	at io.qameta.allure.bamboo.AllureBuildCompleteAction.execute(AllureBuildCompleteAction.java:104)
	at com.atlassian.bamboo.chains.ChainPluginSupportImpl.lambda$chainCompleted$2(ChainPluginSupportImpl.java:139)
	at com.atlassian.bamboo.chains.ChainPluginSupportImpl$1.call(ChainPluginSupportImpl.java:97)
	at com.atlassian.bamboo.chains.ChainPluginSupportImpl$1.call(ChainPluginSupportImpl.java:93)
	at com.atlassian.bamboo.plugin.BambooPluginUtils.callUnsafeCode(BambooPluginUtils.java:55)
	at com.atlassian.bamboo.chains.ChainPluginSupportImpl.callActionFunction(ChainPluginSupportImpl.java:93)
	at com.atlassian.bamboo.chains.ChainPluginSupportImpl.lambda$withCustomVariableContext$0(ChainPluginSupportImpl.java:85)
	at com.atlassian.bamboo.variable.CustomVariableContextImpl.withVariableSubstitutor(CustomVariableContextImpl.java:107)
	at com.atlassian.bamboo.variable.CustomVariableContextRunnerImpl.execute(CustomVariableContextRunnerImpl.java:31)
	at com.atlassian.bamboo.chains.ChainPluginSupportImpl.withCustomVariableContext(ChainPluginSupportImpl.java:85)
	at com.atlassian.bamboo.chains.ChainPluginSupportImpl.chainCompleted(ChainPluginSupportImpl.java:135)
	at sun.reflect.GeneratedMethodAccessor2748.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.orm.hibernate5.support.OpenSessionInterceptor.invoke(OpenSessionInterceptor.java:91)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
	at com.sun.proxy.$Proxy295.chainCompleted(Unknown Source)
	at com.atlassian.bamboo.chains.ChainExecutionManagerImpl.finaliseChainStateIfChainExecutionHasCompleted(ChainExecutionManagerImpl.java:1173)
	at com.atlassian.bamboo.chains.ChainExecutionManagerImpl.access$1700(ChainExecutionManagerImpl.java:141)
	at com.atlassian.bamboo.chains.ChainExecutionManagerImpl$3.run(ChainExecutionManagerImpl.java:709)
	at io.atlassian.util.concurrent.ManagedLocks$ManagedLockImpl.withLock(ManagedLocks.java:302)
	at com.atlassian.bamboo.chains.ChainExecutionManagerImpl.execute(ChainExecutionManagerImpl.java:625)
	at com.atlassian.bamboo.chains.ChainExecutionManagerImpl.access$1300(ChainExecutionManagerImpl.java:141)
	at com.atlassian.bamboo.chains.ChainExecutionManagerImpl$2$1.run(ChainExecutionManagerImpl.java:478)
	at io.atlassian.util.concurrent.ManagedLocks$ManagedLockImpl.withLock(ManagedLocks.java:302)
	at com.atlassian.bamboo.chains.ChainExecutionManagerImpl$2.run(ChainExecutionManagerImpl.java:463)
	at io.atlassian.util.concurrent.ManagedLocks$ManagedLockImpl.withLock(ManagedLocks.java:302)
	at com.atlassian.bamboo.chains.ChainExecutionManagerImpl.onBuildFinished(ChainExecutionManagerImpl.java:449)
	at sun.reflect.GeneratedMethodAccessor2683.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.atlassian.event.internal.SingleParameterMethodListenerInvoker.invoke(SingleParameterMethodListenerInvoker.java:42)
	at com.atlassian.event.internal.ComparableListenerInvoker.invoke(ComparableListenerInvoker.java:48)
	at com.atlassian.event.internal.AsynchronousAbleEventDispatcher.lambda$null$0(AsynchronousAbleEventDispatcher.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at com.atlassian.bamboo.utils.BambooRunnables$1.run(BambooRunnables.java:48)
	at com.atlassian.bamboo.security.ImpersonationHelper.runWith(ImpersonationHelper.java:26)
	at com.atlassian.bamboo.security.ImpersonationHelper.runWithSystemAuthority(ImpersonationHelper.java:17)
	at com.atlassian.bamboo.security.ImpersonationHelper$1.run(ImpersonationHelper.java:41)
	at java.lang.Thread.run(Thread.java:750)
Caused by: org.buildobjects.process.ExternalProcessFailureException: External process '/bin/bash /tmp/allure/allure-2.23.1/binary/bin/allure generate -o /opt/local/bmbapp/bamboo/temp/1693228298710-1/report /opt/local/bmbapp/bamboo/temp/1693228298710-0/10c6933b-f925-4a03-be73-7497790bffa8' returned 1 after 78ms
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000005c0000000, 8589934592, 0) failed; error='Cannot allocate memory' (errno=12)

	at org.buildobjects.process.Proc.<init>(Proc.java:108)
	at org.buildobjects.process.ProcBuilder.run(ProcBuilder.java:193)
	at io.qameta.allure.bamboo.AllureCommandLineSupport.runCommand(AllureCommandLineSupport.java:22)
	at io.qameta.allure.bamboo.AllureExecutable.generate(AllureExecutable.java:33)
	... 45 more

### Steps to Reproduce

<html>
<body>

custom.allure.build.report.output | java.lang.RuntimeException: Failed to generate allure report at io.qameta.allure.bamboo.AllureExecutable.generate(AllureExecutable.java:40) at io.qameta.allure.bamboo.AllureBuildCompleteAction.execute(AllureBuildCompleteAction.java:104) at com.atlassian.bamboo.chains.ChainPluginSupportImpl.lambda$chainCompleted$2(ChainPluginSupportImpl.java:139) at com.atlassian.bamboo.chains.ChainPluginSupportImpl$1.call(ChainPluginSupportImpl.java:97) at com.atlassian.bamboo.chains.ChainPluginSupportImpl$1.call(ChainPluginSupportImpl.java:93) at com.atlassian.bamboo.plugin.BambooPluginUtils.callUnsafeCode(BambooPluginUtils.java:55) at com.atlassian.bamboo.chains.ChainPluginSupportImpl.callActionFunction(ChainPluginSupportImpl.java:93) at com.atlassian.bamboo.chains.ChainPluginSupportImpl.lambda$withCustomVariableContext$0(ChainPluginSupportImpl.java:85) at com.atlassian.bamboo.variable.CustomVariableContextImpl.withVariableSubstitutor(CustomVariableContextImpl.java:107) at com.atlassian.bamboo.variable.CustomVariableContextRunnerImpl.execute(CustomVariableContextRunnerImpl.java:31) at com.atlassian.bamboo.chains.ChainPluginSupportImpl.withCustomVariableContext(ChainPluginSupportImpl.java:85) at com.atlassian.bamboo.chains.ChainPluginSupportImpl.chainCompleted(ChainPluginSupportImpl.java:135) at sun.reflect.GeneratedMethodAccessor2748.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344) at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) at org.springframework.orm.hibernate5.support.OpenSessionInterceptor.invoke(OpenSessionInterceptor.java:91) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215) at com.sun.proxy.$Proxy295.chainCompleted(Unknown Source) at com.atlassian.bamboo.chains.ChainExecutionManagerImpl.finaliseChainStateIfChainExecutionHasCompleted(ChainExecutionManagerImpl.java:1173) at com.atlassian.bamboo.chains.ChainExecutionManagerImpl.access$1700(ChainExecutionManagerImpl.java:141) at com.atlassian.bamboo.chains.ChainExecutionManagerImpl$3.run(ChainExecutionManagerImpl.java:709) at io.atlassian.util.concurrent.ManagedLocks$ManagedLockImpl.withLock(ManagedLocks.java:302) at com.atlassian.bamboo.chains.ChainExecutionManagerImpl.execute(ChainExecutionManagerImpl.java:625) at com.atlassian.bamboo.chains.ChainExecutionManagerImpl.access$1300(ChainExecutionManagerImpl.java:141) at com.atlassian.bamboo.chains.ChainExecutionManagerImpl$2$1.run(ChainExecutionManagerImpl.java:478) at io.atlassian.util.concurrent.ManagedLocks$ManagedLockImpl.withLock(ManagedLocks.java:302) at com.atlassian.bamboo.chains.ChainExecutionManagerImpl$2.run(ChainExecutionManagerImpl.java:463) at io.atlassian.util.concurrent.ManagedLocks$ManagedLockImpl.withLock(ManagedLocks.java:302) at com.atlassian.bamboo.chains.ChainExecutionManagerImpl.onBuildFinished(ChainExecutionManagerImpl.java:449) at sun.reflect.GeneratedMethodAccessor2683.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at com.atlassian.event.internal.SingleParameterMethodListenerInvoker.invoke(SingleParameterMethodListenerInvoker.java:42) at com.atlassian.event.internal.ComparableListenerInvoker.invoke(ComparableListenerInvoker.java:48) at com.atlassian.event.internal.AsynchronousAbleEventDispatcher.lambda$null$0(AsynchronousAbleEventDispatcher.java:37) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at com.atlassian.bamboo.utils.BambooRunnables$1.run(BambooRunnables.java:48) at com.atlassian.bamboo.security.ImpersonationHelper.runWith(ImpersonationHelper.java:26) at com.atlassian.bamboo.security.ImpersonationHelper.runWithSystemAuthority(ImpersonationHelper.java:17) at com.atlassian.bamboo.security.ImpersonationHelper$1.run(ImpersonationHelper.java:41) at java.lang.Thread.run(Thread.java:750) Caused by: org.buildobjects.process.ExternalProcessFailureException: External process '/bin/bash /tmp/allure/allure-2.23.1/binary/bin/allure generate -o /opt/local/bmbapp/bamboo/temp/1693228298710-1/report /opt/local/bmbapp/bamboo/temp/1693228298710-0/10c6933b-f925-4a03-be73-7497790bffa8' returned 1 after 78ms OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000005c0000000, 8589934592, 0) failed; error='Cannot allocate memory' (errno=12) at org.buildobjects.process.Proc.<init>(Proc.java:108) at org.buildobjects.process.ProcBuilder.run(ProcBuilder.java:193) at io.qameta.allure.bamboo.AllureCommandLineSupport.runCommand(AllureCommandLineSupport.java:22) at io.qameta.allure.bamboo.AllureExecutable.generate(AllureExecutable.java:33) ... 45 more
-- | --

</body>
</html>

### Expected Behaviour

<html>
<body>

custom.allure.build.report.output | java.lang.RuntimeException: Failed to generate allure report at io.qameta.allure.bamboo.AllureExecutable.generate(AllureExecutable.java:40) at io.qameta.allure.bamboo.AllureBuildCompleteAction.execute(AllureBuildCompleteAction.java:104) at com.atlassian.bamboo.chains.ChainPluginSupportImpl.lambda$chainCompleted$2(ChainPluginSupportImpl.java:139) at com.atlassian.bamboo.chains.ChainPluginSupportImpl$1.call(ChainPluginSupportImpl.java:97) at com.atlassian.bamboo.chains.ChainPluginSupportImpl$1.call(ChainPluginSupportImpl.java:93) at com.atlassian.bamboo.plugin.BambooPluginUtils.callUnsafeCode(BambooPluginUtils.java:55) at com.atlassian.bamboo.chains.ChainPluginSupportImpl.callActionFunction(ChainPluginSupportImpl.java:93) at com.atlassian.bamboo.chains.ChainPluginSupportImpl.lambda$withCustomVariableContext$0(ChainPluginSupportImpl.java:85) at com.atlassian.bamboo.variable.CustomVariableContextImpl.withVariableSubstitutor(CustomVariableContextImpl.java:107) at com.atlassian.bamboo.variable.CustomVariableContextRunnerImpl.execute(CustomVariableContextRunnerImpl.java:31) at com.atlassian.bamboo.chains.ChainPluginSupportImpl.withCustomVariableContext(ChainPluginSupportImpl.java:85) at com.atlassian.bamboo.chains.ChainPluginSupportImpl.chainCompleted(ChainPluginSupportImpl.java:135) at sun.reflect.GeneratedMethodAccessor2748.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344) at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) at org.springframework.orm.hibernate5.support.OpenSessionInterceptor.invoke(OpenSessionInterceptor.java:91) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215) at com.sun.proxy.$Proxy295.chainCompleted(Unknown Source) at com.atlassian.bamboo.chains.ChainExecutionManagerImpl.finaliseChainStateIfChainExecutionHasCompleted(ChainExecutionManagerImpl.java:1173) at com.atlassian.bamboo.chains.ChainExecutionManagerImpl.access$1700(ChainExecutionManagerImpl.java:141) at com.atlassian.bamboo.chains.ChainExecutionManagerImpl$3.run(ChainExecutionManagerImpl.java:709) at io.atlassian.util.concurrent.ManagedLocks$ManagedLockImpl.withLock(ManagedLocks.java:302) at com.atlassian.bamboo.chains.ChainExecutionManagerImpl.execute(ChainExecutionManagerImpl.java:625) at com.atlassian.bamboo.chains.ChainExecutionManagerImpl.access$1300(ChainExecutionManagerImpl.java:141) at com.atlassian.bamboo.chains.ChainExecutionManagerImpl$2$1.run(ChainExecutionManagerImpl.java:478) at io.atlassian.util.concurrent.ManagedLocks$ManagedLockImpl.withLock(ManagedLocks.java:302) at com.atlassian.bamboo.chains.ChainExecutionManagerImpl$2.run(ChainExecutionManagerImpl.java:463) at io.atlassian.util.concurrent.ManagedLocks$ManagedLockImpl.withLock(ManagedLocks.java:302) at com.atlassian.bamboo.chains.ChainExecutionManagerImpl.onBuildFinished(ChainExecutionManagerImpl.java:449) at sun.reflect.GeneratedMethodAccessor2683.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at com.atlassian.event.internal.SingleParameterMethodListenerInvoker.invoke(SingleParameterMethodListenerInvoker.java:42) at com.atlassian.event.internal.ComparableListenerInvoker.invoke(ComparableListenerInvoker.java:48) at com.atlassian.event.internal.AsynchronousAbleEventDispatcher.lambda$null$0(AsynchronousAbleEventDispatcher.java:37) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at com.atlassian.bamboo.utils.BambooRunnables$1.run(BambooRunnables.java:48) at com.atlassian.bamboo.security.ImpersonationHelper.runWith(ImpersonationHelper.java:26) at com.atlassian.bamboo.security.ImpersonationHelper.runWithSystemAuthority(ImpersonationHelper.java:17) at com.atlassian.bamboo.security.ImpersonationHelper$1.run(ImpersonationHelper.java:41) at java.lang.Thread.run(Thread.java:750) Caused by: org.buildobjects.process.ExternalProcessFailureException: External process '/bin/bash /tmp/allure/allure-2.23.1/binary/bin/allure generate -o /opt/local/bmbapp/bamboo/temp/1693228298710-1/report /opt/local/bmbapp/bamboo/temp/1693228298710-0/10c6933b-f925-4a03-be73-7497790bffa8' returned 1 after 78ms OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000005c0000000, 8589934592, 0) failed; error='Cannot allocate memory' (errno=12) at org.buildobjects.process.Proc.<init>(Proc.java:108) at org.buildobjects.process.ProcBuilder.run(ProcBuilder.java:193) at io.qameta.allure.bamboo.AllureCommandLineSupport.runCommand(AllureCommandLineSupport.java:22) at io.qameta.allure.bamboo.AllureExecutable.generate(AllureExecutable.java:33) ... 45 more
-- | --

</body>
</html>

### Screenshots or Additional Context

Something went wrong with Allure Report generation. Here are some details: 
java.lang.RuntimeException: Failed to generate allure report
	at io.qameta.allure.bamboo.AllureExecutable.generate(AllureExecutable.java:40)
	at io.qameta.allure.bamboo.AllureBuildCompleteAction.execute(AllureBuildCompleteAction.java:104)
	at com.atlassian.bamboo.chains.ChainPluginSupportImpl.lambda$chainCompleted$2(ChainPluginSupportImpl.java:139)
	at com.atlassian.bamboo.chains.ChainPluginSupportImpl$1.call(ChainPluginSupportImpl.java:97)
	at com.atlassian.bamboo.chains.ChainPluginSupportImpl$1.call(ChainPluginSupportImpl.java:93)
	at com.atlassian.bamboo.plugin.BambooPluginUtils.callUnsafeCode(BambooPluginUtils.java:55)
	at com.atlassian.bamboo.chains.ChainPluginSupportImpl.callActionFunction(ChainPluginSupportImpl.java:93)
	at com.atlassian.bamboo.chains.ChainPluginSupportImpl.lambda$withCustomVariableContext$0(ChainPluginSupportImpl.java:85)
	at com.atlassian.bamboo.variable.CustomVariableContextImpl.withVariableSubstitutor(CustomVariableContextImpl.java:107)
	at com.atlassian.bamboo.variable.CustomVariableContextRunnerImpl.execute(CustomVariableContextRunnerImpl.java:31)
	at com.atlassian.bamboo.chains.ChainPluginSupportImpl.withCustomVariableContext(ChainPluginSupportImpl.java:85)
	at com.atlassian.bamboo.chains.ChainPluginSupportImpl.chainCompleted(ChainPluginSupportImpl.java:135)
	at sun.reflect.GeneratedMethodAccessor2748.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.orm.hibernate5.support.OpenSessionInterceptor.invoke(OpenSessionInterceptor.java:91)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
	at com.sun.proxy.$Proxy295.chainCompleted(Unknown Source)
	at com.atlassian.bamboo.chains.ChainExecutionManagerImpl.finaliseChainStateIfChainExecutionHasCompleted(ChainExecutionManagerImpl.java:1173)
	at com.atlassian.bamboo.chains.ChainExecutionManagerImpl.access$1700(ChainExecutionManagerImpl.java:141)
	at com.atlassian.bamboo.chains.ChainExecutionManagerImpl$3.run(ChainExecutionManagerImpl.java:709)
	at io.atlassian.util.concurrent.ManagedLocks$ManagedLockImpl.withLock(ManagedLocks.java:302)
	at com.atlassian.bamboo.chains.ChainExecutionManagerImpl.execute(ChainExecutionManagerImpl.java:625)
	at com.atlassian.bamboo.chains.ChainExecutionManagerImpl.access$1300(ChainExecutionManagerImpl.java:141)
	at com.atlassian.bamboo.chains.ChainExecutionManagerImpl$2$1.run(ChainExecutionManagerImpl.java:478)
	at io.atlassian.util.concurrent.ManagedLocks$ManagedLockImpl.withLock(ManagedLocks.java:302)
	at com.atlassian.bamboo.chains.ChainExecutionManagerImpl$2.run(ChainExecutionManagerImpl.java:463)
	at io.atlassian.util.concurrent.ManagedLocks$ManagedLockImpl.withLock(ManagedLocks.java:302)
	at com.atlassian.bamboo.chains.ChainExecutionManagerImpl.onBuildFinished(ChainExecutionManagerImpl.java:449)
	at sun.reflect.GeneratedMethodAccessor2683.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.atlassian.event.internal.SingleParameterMethodListenerInvoker.invoke(SingleParameterMethodListenerInvoker.java:42)
	at com.atlassian.event.internal.ComparableListenerInvoker.invoke(ComparableListenerInvoker.java:48)
	at com.atlassian.event.internal.AsynchronousAbleEventDispatcher.lambda$null$0(AsynchronousAbleEventDispatcher.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at com.atlassian.bamboo.utils.BambooRunnables$1.run(BambooRunnables.java:48)
	at com.atlassian.bamboo.security.ImpersonationHelper.runWith(ImpersonationHelper.java:26)
	at com.atlassian.bamboo.security.ImpersonationHelper.runWithSystemAuthority(ImpersonationHelper.java:17)
	at com.atlassian.bamboo.security.ImpersonationHelper$1.run(ImpersonationHelper.java:41)
	at java.lang.Thread.run(Thread.java:750)
Caused by: org.buildobjects.process.ExternalProcessFailureException: External process '/bin/bash /tmp/allure/allure-2.23.1/binary/bin/allure generate -o /opt/local/bmbapp/bamboo/temp/1693228298710-1/report /opt/local/bmbapp/bamboo/temp/1693228298710-0/10c6933b-f925-4a03-be73-7497790bffa8' returned 1 after 78ms
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000005c0000000, 8589934592, 0) failed; error='Cannot allocate memory' (errno=12)

	at org.buildobjects.process.Proc.<init>(Proc.java:108)
	at org.buildobjects.process.ProcBuilder.run(ProcBuilder.java:193)
	at io.qameta.allure.bamboo.AllureCommandLineSupport.runCommand(AllureCommandLineSupport.java:22)
	at io.qameta.allure.bamboo.AllureExecutable.generate(AllureExecutable.java:33)
	... 45 more

### What Language are you using?

Java

### What Framework/Allure Integration you are using?

Testng

### What version of Allure Integration you are using?

2.22.3

### What version of Allure Report you are using?

2.22.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by baev** [comment]
> External process '/bin/bash /tmp/allure/allure-2.23.1/binary/bin/allure generate -o /opt/local/bmbapp/bamboo/temp/1693228298710-1/report /opt/local/bmbapp/bamboo/temp/1693228298710-0/10c6933b-f925-4a03-be73-7497790bffa8' returned 1 after 78ms
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000005c0000000, 8589934592, 0) failed; error='Cannot allocate memory' (errno=12)

According to the error, you do not have enough memory to generate the report. Please consider contacting your DEVOPS/SRE team.
