### ISSUE TITLE
Allure for Cypress not working

### ISSUE THREAD

**Issue by harmin-parra** [allure-framework/allure2#2502]
### Describe the Bug

I get this error when running cypress

```
Oops...we found an error preparing this test file:

  > cypress/support/e2e.js

The error was:

Error: Webpack Compilation Error
./cypress/support/e2e.js
Module not found: Error: Can't resolve 'allure-cypress/commands' in '/home/hpr/cypress-allure-plugin-example/cypress/support'
resolve 'allure-cypress/commands' in '/home/hpr/cypress-allure-plugin-example/cypress/support'
  Parsed request is a module
  using description file: /home/hpr/cypress-allure-plugin-example/package.json (relative path: ./cypress/support)
    Field 'browser' doesn't contain a valid alias configuration
    Looked for and couldn't find the file at the following paths:
[/home/hpr/cypress-allure-plugin-example/cypress/support/node_modules]
[/home/hpr/cypress-allure-plugin-example/cypress/node_modules]
[/home/hpr/node_modules]
[/home/node_modules]
[/node_modules]
[/home/hpr/cypress-allure-plugin-example/node_modules/allure-cypress/commands]
[/home/hpr/cypress-allure-plugin-example/node_modules/allure-cypress/commands.js]
[/home/hpr/cypress-allure-plugin-example/node_modules/allure-cypress/commands.json]
[/home/hpr/cypress-allure-plugin-example/node_modules/allure-cypress/commands.jsx]
[/home/hpr/cypress-allure-plugin-example/node_modules/allure-cypress/commands.mjs]
[/home/hpr/cypress-allure-plugin-example/node_modules/allure-cypress/commands.coffee]
 @ ./cypress/support/e2e.js 4:0-34
 
    at handle (/home/hpr/.cache/Cypress/12.14.0/Cypress/resources/app/node_modules/@packages/server/node_modules/@cypress/webpack-preprocessor/dist/index.js:212:23)
    at finalCallback (/home/hpr/.cache/Cypress/12.14.0/Cypress/resources/app/node_modules/webpack/lib/Compiler.js:257:39)
    at /home/hpr/.cache/Cypress/12.14.0/Cypress/resources/app/node_modules/webpack/lib/Compiler.js:306:14
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/hpr/.cache/Cypress/12.14.0/Cypress/resources/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/home/hpr/.cache/Cypress/12.14.0/Cypress/resources/app/node_modules/tapable/lib/Hook.js:154:20)
    at /home/hpr/.cache/Cypress/12.14.0/Cypress/resources/app/node_modules/webpack/lib/Compiler.js:304:22
    at Compiler.emitRecords (/home/hpr/.cache/Cypress/12.14.0/Cypress/resources/app/node_modules/webpack/lib/Compiler.js:499:39)
    at /home/hpr/.cache/Cypress/12.14.0/Cypress/resources/app/node_modules/webpack/lib/Compiler.js:298:10
    at /home/hpr/.cache/Cypress/12.14.0/Cypress/resources/app/node_modules/webpack/lib/Compiler.js:485:14
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/hpr/.cache/Cypress/12.14.0/Cypress/resources/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/home/hpr/.cache/Cypress/12.14.0/Cypress/resources/app/node_modules/tapable/lib/Hook.js:154:20)
    at /home/hpr/.cache/Cypress/12.14.0/Cypress/resources/app/node_modules/webpack/lib/Compiler.js:482:27
    at /home/hpr/.cache/Cypress/12.14.0/Cypress/resources/app/node_modules/neo-async/async.js:2818:7
    at done (/home/hpr/.cache/Cypress/12.14.0/Cypress/resources/app/node_modules/neo-async/async.js:3522:9)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/hpr/.cache/Cypress/12.14.0/Cypress/resources/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/home/hpr/.cache/Cypress/12.14.0/Cypress/resources/app/node_modules/tapable/lib/Hook.js:154:20)
    at /home/hpr/.cache/Cypress/12.14.0/Cypress/resources/app/node_modules/webpack/lib/Compiler.js:464:33
    at /home/hpr/.cache/Cypress/12.14.0/Cypress/resources/app/node_modules/@packages/server/node_modules/graceful-fs/graceful-fs.js:143:16
    at /home/hpr/.cache/Cypress/12.14.0/Cypress/resources/app/node_modules/@packages/server/node_modules/graceful-fs/graceful-fs.js:143:16
    at /home/hpr/.cache/Cypress/12.14.0/Cypress/resources/app/node_modules/@packages/server/node_modules/graceful-fs/graceful-fs.js:61:14
    at FSReqCallback.oncomplete (node:fs:192:23)

This occurred while Cypress was compiling and bundling your test code. This is usually caused by:

- A missing file or dependency
- A syntax error in the file or one of its dependencies

Fix the error in your code and re-run your tests.
```

### Steps to Reproduce

`npm install --save-dev allure-cypress`

**cypress/support/e2e.js** file

```
import './commands';
import "allure-cypress/commands";

```
**cypress.config.js** file:

```
const { defineConfig } = require('cypress');
const { allureCypress } = require("allure-cypress/reporter");

module.exports = defineConfig({

    env: {
        issuePrefix: 'https://your.domain.atlassian.net/browse/',
        tmsPrefix: 'https://some.testrail.instance/path/suite/caseID-'
    },
  video: false,
    e2e: {
        experimentalStudio: true,
        specPattern: 'cypress/tests/**/*.cy.{js,jsx,ts,tsx}',
        setupNodeEvents: async function (on, config) {
            allureCypress(on);
            return config;
        }
    }

```

`npx cypress run --browser=electron`

### Expected Behaviour

cypress runs without errors and aluure report is generated

### What Language are you using?

JavaScript

### What Framework/Allure Integration you are using?

allure-cypress 2.15.1

### What version of Allure Integration you are using?

2.15.1

### What version of Allure Report you are using?

2.27.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bhadmusautomates** [comment]
I am experiencing the same issue, is there a solution in the near future?
