### ISSUE TITLE
The json composition yields an exception.

### ISSUE THREAD

**Issue by sailichev** [allure-framework/allure2#254]
[__.zip](https://github.com/allure-framework/allure2/files/916371/__.zip)

```
Exception in thread "main" java.lang.NullPointerException
        at io.qameta.allure.allure2.Allure2Plugin.lambda$static$0(Allure2Plugin.java:48)
        at java.util.Comparator.lambda$comparingLong$6043328a$1(Unknown Source)
        at java.util.TimSort.countRunAndMakeAscending(Unknown Source)
        at java.util.TimSort.sort(Unknown Source)
        at java.util.Arrays.sort(Unknown Source)
        at java.util.stream.SortedOps$SizedRefSortingSink.end(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.forEach(Unknown Source)
        at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.collect(Unknown Source)
        at io.qameta.allure.allure2.Allure2Plugin.getStages(Allure2Plugin.java:204)
        at io.qameta.allure.allure2.Allure2Plugin.convert(Allure2Plugin.java:85)
        at io.qameta.allure.allure2.Allure2Plugin.lambda$readResults$1(Allure2Plugin.java:58)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.forEach(Unknown Source)
        at io.qameta.allure.allure2.Allure2Plugin.readResults(Allure2Plugin.java:58)
        at io.qameta.allure.ReportGenerator.lambda$readResults$0(ReportGenerator.java:27)
        at java.util.ArrayList.forEach(Unknown Source)
        at io.qameta.allure.ReportGenerator.readResults(ReportGenerator.java:27)
        at io.qameta.allure.ReportGenerator.lambda$generate$1(ReportGenerator.java:48)
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.collect(Unknown Source)
        at io.qameta.allure.ReportGenerator.generate(ReportGenerator.java:49)
        at io.qameta.allure.ReportGenerator.generate(ReportGenerator.java:38)
        at io.qameta.allure.Commands.generate(Commands.java:55)
        at io.qameta.allure.Commands.serve(Commands.java:78)
        at io.qameta.allure.CommandLine.run(CommandLine.java:128)
        at java.util.Optional.orElseGet(Unknown Source)
        at io.qameta.allure.CommandLine.main(CommandLine.java:72)

```

**Comment by baev** [comment]
The problem is that you are not set time for `before` and `after` in test container. BTW that is a bug, so thank you

**Comment by baev** [comment]
Also there are no more `befores` and `afters` in test result
