### ISSUE TITLE
Commandline called twice on same results throws Exception

### ISSUE THREAD

**Issue by eroshenkoam** [allure-framework/allure2#264]
`$ allure generate target/allure-results`
```
Report successfully generated to allure-report
```

`$ allure generate target/allure-results`
```
Could not generate report: {}
java.nio.file.FileAlreadyExistsException: allure-report/plugins/behaviors/index.js
	at sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:551)
	at sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:253)
	at java.nio.file.Files.copy(Files.java:1274)
	at io.qameta.allure.util.CopyVisitor.visitFile(CopyVisitor.java:35)
	at io.qameta.allure.util.CopyVisitor.visitFile(CopyVisitor.java:15)
	at java.nio.file.Files.walkFileTree(Files.java:2670)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at io.qameta.allure.plugin.DefaultPlugin.unpackReportStatic(DefaultPlugin.java:44)
	at io.qameta.allure.core.ReportWebPlugin.writePluginsStatic(ReportWebPlugin.java:48)
	at io.qameta.allure.core.ReportWebPlugin.aggregate(ReportWebPlugin.java:38)
	at io.qameta.allure.ReportGenerator.aggregate(ReportGenerator.java:32)
	at io.qameta.allure.ReportGenerator.generate(ReportGenerator.java:49)
	at io.qameta.allure.ReportGenerator.generate(ReportGenerator.java:37)
	at io.qameta.allure.Commands.generate(Commands.java:55)
	at io.qameta.allure.CommandLine.run(CommandLine.java:121)
	at java.util.Optional.orElseGet(Optional.java:267)
	at io.qameta.allure.CommandLine.main(CommandLine.java:72)
```

**Comment by eroshenkoam** [comment]
Seem's like we need to clean allure-report directory (if already exists) before generating the report.
