### ISSUE TITLE
TestNG @DataProvider throws Exception if it contains calls to methods annotated with @Step

### ISSUE THREAD

**Issue by tuulahdus** [allure-framework/allure2#418]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
TestNG method annotated with ```@DataProvider``` throws exception if it contains call to a method with ```@Step``` annotation
java.lang.NullPointerException: Can't get item from storage: uuid can't be null
#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
```java
import io.qameta.allure.Step;
import org.testng.Assert;
import org.testng.annotations.DataProvider;
import org.testng.annotations.Test;

public class TestNGDataProviderCase extends Assert {
    @Step
    public void doSome(){

    }

    @DataProvider
    public Object[][] testDataProvider() {
        doSome();
        return new Object[][] {
                new Object[] {"Success"}
        };
    }

    @Test(dataProvider = "testDataProvider")
    public void reproducibleTest(String value) {
        assertTrue(value.equals("Success"));
    }
}
```

#### What is the expected behavior?
DataProvider shouldn't fail

#### Please tell us about your environment:

- Allure version:        2.0-BETA10
- Test framework:        testng@6.9.12
- Allure adaptor:        allure-testng@2.0-BETA10

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)
```
java.lang.RuntimeException: java.lang.NullPointerException: Can't get item from storage: uuid can't be null
	at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:45)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:110)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:429)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1240)
	at org.testng.internal.Invoker.createParameters(Invoker.java:980)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1070)
	tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:127)
Caused by: java.lang.NullPointerException: Can't get item from storage: uuid can't be null
	at java.util.Objects.requireNonNull(Objects.java:228)
	at io.qameta.allure.internal.AllureStorage.get(AllureStorage.java:110)
	at io.qameta.allure.internal.AllureStorage.addStep(AllureStorage.java:96)
	at io.qameta.allure.AllureLifecycle.startStep(AllureLifecycle.java:202)
	at io.qameta.allure.AllureLifecycle.startStep(AllureLifecycle.java:194)
	at io.qameta.allure.aspects.StepsAspects.stepStart(StepsAspects.java:58)
	at nl.afterpay.tests.TestNGDataProviderCase.doSome(TestNGDataProviderCase.java:12)
	at nl.afterpay.tests.TestNGDataProviderCase.testDataProvider(TestNGDataProviderCase.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:51)
	at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:41)
	... 21 more ```

**Comment by baev** [comment]
See the following issues:

- NPE: https://github.com/allure-framework/allure-java/issues/68
- Steps in data providers: https://github.com/allure-framework/allure-java/issues/47

**Comment by L-Evg** [comment]
The same NPE in case of `@Attachment` annotation.
