### ISSUE TITLE
Getting there is no severity level {} failing back to 'normal' exception when I don't specified a severity tag in all cucumber feature files

### ISSUE THREAD

**Issue by thasherwin** [allure-framework/allure2#459]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
When I run a mvn clean test using cucumber jvm and junit having only one @severity=blocker tag in a .feature and no severity tag in other .feature files, i get warings:
 

> There is no severity level {} failing back to 'normal'
> java.lang.IllegalArgumentException: No enum constant io.qameta.allure.SeverityLevel.blocker

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal 

1. Add at least two feature files in a cucumber JVM junit project and add only one @severity=blocker tag

2. Run mvn clean test

#### What is the expected behavior?
No exception related to the severity is shown in the console

#### What is the motivation / use case for changing the behavior?
Allure should fill in on every test that does not contain a severity tag default normal without giving me feedback

#### Please tell us about your environment:

| Allure version | 2.2.0 |
| --- | --- |
| Test framework | testng@6.8 |
| Allure cucumber jvm| allure-junit@2.0-BETA14 |
| Generate report using | allure-maven@2.18 |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

> 2017-07-05 16:03:20:715] [main] WARN LabelBuilder - There is no severity level {} failing back to 'normal'
java.lang.IllegalArgumentException: No enum constant io.qameta.allure.SeverityLevel.blocker
        at java.lang.Enum.valueOf(Enum.java:238)
        at io.qameta.allure.SeverityLevel.valueOf(SeverityLevel.java:6)
        at io.qameta.allure.cucumberjvm.LabelBuilder$2.value(LabelBuilder.java:101)
        at io.qameta.allure.util.ResultsUtils.createLabel(ResultsUtils.java:69)
        at io.qameta.allure.cucumberjvm.LabelBuilder.getSeverityLabel(LabelBuilder.java:97)
        at io.qameta.allure.cucumberjvm.LabelBuilder.<init>(LabelBuilder.java:55)
        at io.qameta.allure.cucumberjvm.AllureCucumberJvm.startOfScenarioLifeCycle(AllureCucumberJvm.java:90)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at cucumber.runtime.Utils$1.call(Utils.java:40)
        at cucumber.runtime.Timeout.timeout(Timeout.java:16)
        at cucumber.runtime.Utils.invoke(Utils.java:34)
        at cucumber.runtime.RuntimeOptions$1.invoke(RuntimeOptions.java:294)
        at com.sun.proxy.$Proxy22.startOfScenarioLifeCycle(Unknown Source)
        at cucumber.runtime.junit.JUnitReporter.startOfScenarioLifeCycle(JUnitReporter.java:238)
        at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:39)
        at cucumber.runtime.junit.ExecutionUnitRunner.run(ExecutionUnitRunner.java:102)
        at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:63)
        at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:18)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:70)
        at cucumber.api.junit.Cucumber.runChild(Cucumber.java:95)
        at cucumber.api.junit.Cucumber.runChild(Cucumber.java:38)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at cucumber.api.junit.Cucumber.run(Cucumber.java:100)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:272)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:236)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)

**Comment by baev** [comment]
should be fixed in allure-java:2.0-BETA15

**Comment by thasherwin** [comment]
Great. That was fast
