### ISSUE TITLE
NPE when null is test Parameter (from dataprovider)

### ISSUE THREAD

**Issue by dimkin-eu** [allure-framework/allure2#539]
#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
test, running from dataprovider, where data could have null-s - fails with NPE

#### What is the expected behavior?
Having null as parameter not hurting for test

#### Please tell us about your environment:

| Allure version | 2.3.1 |
| --- | --- |
| Test framework | testng@6.8 |
| Allure adaptor | allure-testng@2.0-BETA16 |
| Generate report using | allure-maven@2.18 |

#### Other information 

```
java.lang.NullPointerException
    at io.qameta.allure.aspects.Allure1Annotations.getMethodParameters(Allure1Annotations.java:104)
    at io.qameta.allure.aspects.Allure1Annotations.getParameters(Allure1Annotations.java:95)
    at io.qameta.allure.aspects.Allure1Annotations.updateParameters(Allure1Annotations.java:85)
    at io.qameta.allure.AllureLifecycle.lambda$updateTestCase$10(AllureLifecycle.java:178)
    at java.util.Optional.ifPresent(Optional.java:159)
    at io.qameta.allure.AllureLifecycle.updateTestCase(AllureLifecycle.java:176)
    at io.qameta.allure.aspects.Allure1TestCaseAspects.lambda$updateTestCase$0(Allure1TestCaseAspects.java:38)
    at java.util.Optional.ifPresent(Optional.java:159)
    at io.qameta.allure.aspects.Allure1TestCaseAspects.updateTestCase(Allure1TestCaseAspects.java:35)
    at io.qameta.allure.aspects.Allure1TestCaseAspects.testNgTestStart(Allure1TestCaseAspects.java:27)
```

**Comment by dimkin-eu** [comment]
moved to https://github.com/allure-framework/allure-java/issues/129
