### ISSUE TITLE
Multiple errors in generation process, but generation is success

### ISSUE THREAD

**Issue by akriuchk** [allure-framework/allure2#549]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
In command line, after "allure generate --clean" multiple errors (example below) are present. But report generated successfully.

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
0. Checkout project from SVN
1. Run testng framework with maven witch 'clean test' parameters
2. Place results to ./report/results-source folder
3. Execute allure from test resources ./src/test/resources/reporting/allure/bin/allure generate --clean ./report/results-source -o ./report/results

#### What is the expected behavior?
Report generated without errors on Linux, using checkout from SVN

#### Please tell us about your environment:

| Allure version | 2.3.3 |
| --- | --- |
| Test framework | testng@6.8 |
| Allure adaptor | allure-testng@2.0-BETA11 |
| Generate report using | allure-maven@2.18 |
|---|---|
| Java | 1.8.0_131 |
| Linux | 4.4.0-78-generic |

#### Other information 
Could not copy file
21:38:09 java.nio.file.NoSuchFileException: ./report/results/plugins/behaviors/.svn/prop-base/index.js.svn-base
21:38:09       at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
21:38:09     at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
21:38:09     at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
21:38:09     at sun.nio.fs.UnixCopyFile.copyFile(UnixCopyFile.java:243)
21:38:09     at sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:581)
21:38:09     at sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:253)
21:38:09     at java.nio.file.Files.copy(Files.java:1274)
21:38:09     at io.qameta.allure.util.CopyVisitor.visitFile(CopyVisitor.java:49)
21:38:09     at io.qameta.allure.util.CopyVisitor.visitFile(CopyVisitor.java:19)
21:38:09     at java.nio.file.Files.walkFileTree(Files.java:2670)
21:38:09     at java.nio.file.Files.walkFileTree(Files.java:2742)
21:38:09     at io.qameta.allure.plugin.DefaultPlugin.unpackReportStatic(DefaultPlugin.java:44)
21:38:09     at io.qameta.allure.core.ReportWebPlugin.writePluginsStatic(ReportWebPlugin.java:48)
21:38:09     at io.qameta.allure.core.ReportWebPlugin.aggregate(ReportWebPlugin.java:38)
21:38:09     at io.qameta.allure.ReportGenerator.aggregate(ReportGenerator.java:38)
21:38:09     at io.qameta.allure.ReportGenerator.generate(ReportGenerator.java:55)
21:38:09     at io.qameta.allure.ReportGenerator.generate(ReportGenerator.java:43)
21:38:09     at io.qameta.allure.Commands.generate(Commands.java:88)
21:38:09     at io.qameta.allure.CommandLine.run(CommandLine.java:129)
21:38:09     at java.util.Optional.orElseGet(Optional.java:267)
21:38:09     at io.qameta.allure.CommandLine.main(CommandLine.java:72)

And many other files;
21:38:09 java.nio.file.NoSuchFileException: ./report/results/plugins/behaviors/.svn/prop-base/index.js.svn-base
21:38:09 java.nio.file.NoSuchFileException: ./report/results/plugins/behaviors/.svn/format
21:38:09 java.nio.file.NoSuchFileException: ./report/results/plugins/behaviors/.svn/all-wcprops
21:38:09 java.nio.file.NoSuchFileException: ./report/results/plugins/behaviors/.svn/entries
21:38:09 java.nio.file.NoSuchFileException: ./report/results/plugins/behaviors/.svn/text-base/index.js.svn-base
21:38:09 java.nio.file.NoSuchFileException: ./report/results/plugins/packages/.svn/prop-base/index.js.svn-base
21:38:09 java.nio.file.NoSuchFileException: ./report/results/plugins/packages/.svn/format
21:38:09 java.nio.file.NoSuchFileException: ./report/results/plugins/packages/.svn/all-wcprops
21:38:09 java.nio.file.NoSuchFileException: ./report/results/plugins/packages/.svn/entries
21:38:09 java.nio.file.NoSuchFileException: ./report/results/plugins/packages/.svn/text-base/index.js.svn-base
21:38:09 java.nio.file.NoSuchFileException: ./report/results/plugins/screen-diff/.svn/prop-base/index.js.svn-base
21:38:09 java.nio.file.NoSuchFileException: ./report/results/plugins/screen-diff/.svn/prop-base/styles.css.svn-base
21:38:09 java.nio.file.NoSuchFileException: ./report/results/plugins/screen-diff/.svn/format
21:38:09 java.nio.file.NoSuchFileException: ./report/results/plugins/screen-diff/.svn/all-wcprops
21:38:09 java.nio.file.NoSuchFileException: ./report/results/plugins/screen-diff/.svn/entries
21:38:09 java.nio.file.NoSuchFileException: ./report/results/plugins/screen-diff/.svn/text-base/index.js.svn-base
21:38:09 java.nio.file.NoSuchFileException: ./report/results/plugins/screen-diff/.svn/text-base/styles.css.svn-base

**Comment by klamping** [comment]
Confirming this is an issue. Any XML file seems to get logged, but the report still "successfully" generates (even if the result isn't usable)
