### ISSUE TITLE
NoClassDefFoundError AbstractTreeAggregator while using `allure serve` 

### ISSUE THREAD

**Issue by dimkin-eu** [allure-framework/allure2#561]
#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request 

#### What is the current behavior?
running `allure serve target/allure-results` in win cli throws NoClassDefFoundError (see below)

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
try to run  `allure serve target/allure-results` for allure 2.3-2.3.3 versions
solution - rolling back to 2.2.1 
- you can install any version in scoop using something like `scoop install allure@2.2.1`

#### What is the expected behavior?
report created

#### Please tell us about your environment:

| Allure version | 2.3.1 |
| --- | --- |
| Test framework | testng@6.8 |
| Allure adaptor | allure-testng@2.0-BETA16 |
| Generate report using | allure-maven@2.18 |
|Scoop|latest version (no updates available)|
|Win|win 10 pro|

#### Other information 

```
Generating report to temp directory...
Exception in thread "main" java.lang.NoClassDefFoundError: io/qameta/allure/tree/AbstractTreeAggregator
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at io.qameta.allure.plugin.DefaultPluginLoader.load(DefaultPluginLoader.java:58)
        at io.qameta.allure.plugin.DefaultPluginLoader.lambda$loadPlugin$0(DefaultPluginLoader.java:42)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at io.qameta.allure.plugin.DefaultPluginLoader.loadPlugin(DefaultPluginLoader.java:45)
        at io.qameta.allure.Commands.lambda$createReportConfiguration$0(Commands.java:176)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at io.qameta.allure.Commands.createReportConfiguration(Commands.java:179)
        at io.qameta.allure.Commands.generate(Commands.java:87)
        at io.qameta.allure.Commands.serve(Commands.java:112)
        at io.qameta.allure.CommandLine.run(CommandLine.java:136)
        at java.util.Optional.orElseGet(Optional.java:267)
        at io.qameta.allure.CommandLine.main(CommandLine.java:72)
Caused by: java.lang.ClassNotFoundException: io.qameta.allure.tree.AbstractTreeAggregator
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 35 more
```

**Comment by baev** [comment]
fixed via https://github.com/lukesampson/scoop/pull/1652
