### ISSUE TITLE
OutOfMemoryError when generate report via allure gradle plugin

### ISSUE THREAD

**Issue by admizh** [allure-framework/allure2#586]
#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request

#### What is the current behavior?
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space, when generate report via gradle allure plugin.

```
allprojects {
    allure {
        version = "2.3.4"
    }
}

task generateReport(type: AllureReport) {
    setGroup("reports")
    reportDir = file(allureReportsDir)
    resultsDirs = [file(allureResultsDir)]
}
```
Trace:
```
16:10:38 Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
16:10:38 	at java.util.Arrays.copyOfRange(Arrays.java:3664)
16:10:38 	at java.lang.String.<init>(String.java:207)
16:10:38 	at com.fasterxml.jackson.core.util.TextBuffer.contentsAsString(TextBuffer.java:344)
16:10:38 	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._finishAndReturnString(UTF8StreamJsonParser.java:2470)
16:10:38 	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.getText(UTF8StreamJsonParser.java:315)
16:10:38 	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:31)
16:10:38 	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:11)
16:10:38 	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:499)
16:10:38 	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:108)
16:10:38 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:276)
16:10:38 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140)
16:10:38 	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:499)
16:10:38 	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:108)
16:10:38 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:276)
16:10:38 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140)
16:10:38 	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:287)
16:10:38 	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:259)
16:10:38 	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:26)
16:10:38 	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:499)
16:10:38 	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:108)
16:10:38 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:276)
16:10:38 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140)
16:10:38 	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:287)
16:10:38 	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:259)
16:10:38 	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:26)
16:10:38 	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:499)
16:10:38 	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:108)
16:10:38 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:276)
16:10:38 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140)
16:10:38 	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:287)
16:10:38 	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:259)
16:10:38 	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:26)

.... 

16:10:45 Exception in thread "main" java.lang.StackOverflowError
16:10:45 	at io.qameta.allure.allure2.Allure2Plugin.lambda$convert$7(Allure2Plugin.java:178)
16:10:45 	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
16:10:45 	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
16:10:45 	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
16:10:45 	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
16:10:45 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
16:10:45 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
16:10:45 	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
16:10:45 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
16:10:45 	at java.util.stream.ReferencePipeline.findAny(ReferencePipeline.java:469)
16:10:45 	at io.qameta.allure.allure2.Allure2Plugin.convert(Allure2Plugin.java:179)
16:10:45 	at io.qameta.allure.allure2.Allure2Plugin.convert(Allure2Plugin.java:165)
16:10:45 	at io.qameta.allure.allure2.Allure2Plugin.lambda$convert$6(Allure2Plugin.java:170)
16:10:45 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
16:10:45 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
16:10:45 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
16:10:45 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
16:10:45 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
16:10:45 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
16:10:45 	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
16:10:45 	at io.qameta.allure.allure2.Allure2Plugin.convert(Allure2Plugin.java:103)
16:10:45 	at io.qameta.allure.allure2.Allure2Plugin.convert(Allure2Plugin.java:170)
16:10:45 	at io.qameta.allure.allure2.Allure2Plugin.lambda$convert$6(Allure2Plugin.java:170)
16:10:45 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
16:10:45 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
16:10:45 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
16:10:45 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
16:10:45 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
16:10:45 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
16:10:45 	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
16:10:45 	at io.qameta.allure.allure2.Allure2Plugin.convert(Allure2Plugin.java:103)
16:10:45 	at io.qameta.allure.allure2.Allure2Plugin.convert(Allure2Plugin.java:170)
16:10:45 	at io.qameta.allure.allure2.Allure2Plugin.lambda$convert$6(Allure2Plugin.java:170)
16:10:45 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
16:10:45 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
16:10:45 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
16:10:45 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
16:10:45 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
16:10:45 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
16:10:45 	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
16:10:45 	at io.qameta.allure.allure2.Allure2Plugin.convert(Allure2Plugin.java:103)
16:10:45 	at io.qameta.allure.allure2.Allure2Plugin.convert(Allure2Plugin.java:170)
16:10:45 	at io.qameta.allure.allure2.Allure2Plugin.lambda$convert$6(Allure2Plugin.java:170)
16:10:45 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
16:10:45 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
16:10:45 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
16:10:45 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
16:10:45 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
16:10:45 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
16:10:45 	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
16:10:45 	at io.qameta.allure.allure2.Allure2Plugin.convert(Allure2Plugin.java:103)
16:10:45 	at io.qameta.allure.allure2.Allure2Plugin.convert(Allure2Plugin.java:170)
16:10:45 	at io.qameta.allure.allure2.Allure2Plugin.lambda$convert$6(Allure2Plugin.java:170)
16:10:45 ERROR: Build step failed with exception
16:10:45 ru.yandex.qatools.allure.jenkins.exception.AllurePluginException: Can not generate Allure Report, exit code: 1
16:10:45 	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.generateReport(AllureReportPublisher.java:265)
16:10:45 	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.perform(AllureReportPublisher.java:186)
16:10:45 	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
16:10:45 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
16:10:45 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:736)
16:10:45 	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:682)
16:10:45 	at hudson.model.Build$BuildExecution.post2(Build.java:186)
16:10:45 	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:627)
16:10:45 	at hudson.model.Run.execute(Run.java:1764)
16:10:45 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
16:10:45 	at hudson.model.ResourceController.execute(ResourceController.java:97)
16:10:45 	at hudson.model.Executor.run(Executor.java:419)

16:10:38 > Process 'command 'C:\***\***\.***\workspace\***\.allure\allure-2.3.4\bin\allure.bat'' finished with non-zero exit value 1
```

| Allure version | 2.3.4 |
| --- | --- |
| Test framework | testng@6.12 |
| Allure adaptor | allure-testng@2.0-BETA17 |
| Gradle version | 4.1 |
| Generate report using | allure-gradle-plugin@2.3.4 |

**Comment by admizh** [comment]
I found root cause of this, its happens after turning on aspects for assertJ. Seems like no any filtering of pointcuts for abstract-soft assertions. try this code:
```
    @Test()
    public void checkSoftAssertions() {
        HashMap<String, String> countriesWithCode = new HashMap<String, String>(){{
            put("RU", "Russia");
        }};
        SoftAssertions softly = new SoftAssertions();
        countriesWithCode.forEach((code, name) -> softly.assertThat(name)
                .as("Country: %s - %s, should be removed from UI", code, name)
                .containsIgnoringCase("Russia"));
        softly.assertAll();
    }

```
