### ISSUE TITLE
NullPointerException on Allure 2.5.0 on Report publishing

### ISSUE THREAD

**Issue by dimkin-eu** [allure-framework/allure2#701]
#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
Job fails with NPE after report is done. Report itself is ok

#### Please tell us about your environment:

| Allure version | 2.5.0 |
| --- | --- |
| Test framework | testng@6.8 |
| Allure adaptor | allure-testng@2.0-BETA16 |
| Allure jenkins plugin | 2.25 |
|Jenkins | 2.95 |

#### Other information 

Happens for matrix job and freestyle job

```
[ci-dc71] $ /home/jenkins/tools/ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation/allure_2_latest/allure-2.5.0/bin/allure generate /home/jenkins/workspace/blabla1/id/3/label/ci-dc71/test-cases/target/allure-results -c -o /home/jenkins/workspace/blabla1/id/3/label/ci-dc71/allure-report
Report successfully generated to /home/jenkins/workspace/blabla1/id/3/label/ci-dc71/allure-report
Allure report was successfully generated.
Creating artifact for the build.
Artifact was added to the build.
ERROR: Build step failed with exception
java.lang.NullPointerException
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.generateReport(AllureReportPublisher.java:308)
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.perform(AllureReportPublisher.java:223)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1752)
	at hudson.matrix.MatrixRun.run(MatrixRun.java:146)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Build step 'Allure Report' marked build as failure
```

```
[RIO_BAC_CIT] $ /home/jenkins/tools/ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation/allure_2_latest/allure-2.5.0/bin/allure generate /home/jenkins/workspace/blabla2/test-cases/target/allure-results -c -o /home/jenkins/workspace/blabla2/allure-report
Report successfully generated to /home/jenkins/workspace/blabla2/allure-report
Allure report was successfully generated.
Creating artifact for the build.
Artifact was added to the build.
ERROR: Build step failed with exception
java.lang.NullPointerException
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.generateReport(AllureReportPublisher.java:308)
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.perform(AllureReportPublisher.java:223)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.post2(MavenModuleSetBuild.java:1073)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1752)
	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:543)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Build step 'Allure Report' marked build as failure
```

**Comment by eroshenkoam** [comment]
Seems like problem in Jenkins plugin, I'm working on release right now. New release solves this problem.

**Comment by eroshenkoam** [comment]
We found the problem in Allure Jenkins plugin. 
I'm making release right now. 
Just few minutes.

**Comment by eroshenkoam** [comment]
I have made the release, so you can download plugin from Jenkins release job: 
https://ci.qameta.io/job/allure-plugin/job/master/68

**Comment by eroshenkoam** [comment]
@dimkin-eu ty 🥇
