### ISSUE TITLE
404 Not Found on report overview

### ISSUE THREAD

**Issue by mdfaller** [allure-framework/allure2#718]
#### I'm submitting a ... 
  - [x ] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
I get a 404 on the report's overview page. The rest of the report functions normally. All expected test data and attachments are present.

The overview actually loads correctly for a brief moment and displays all the graphs and information, but then the 404 appears.

#### What is the expected behavior?
Show the overview

#### Please tell us about your environment:

| Allure version | 2.4.1 AND 2.5.0 |
| Test framework | testng@6.8 |
| Allure adaptor | allure-testng@2.0-BETA19 |
| Generate report using | allure-maven@2.9 and AND allure-jenkins@2.25.1 |
| Browsers | chrome@63.0.3239.108 AND firefox@57.0 |

#### Other information 
Chrome console shows two errors
```
jQuery.Deferred exception: Cannot read property 'total' of undefined TypeError: Cannot read property 'total' of undefined
    at file:///C:/Users/mfaller/Downloads/allure-report/app.js:37:132264
    at Array.map (<anonymous>)
    at e.value (file:///C:/Users/mfaller/Downloads/allure-report/app.js:37:132151)
    at e.value (file:///C:/Users/mfaller/Downloads/allure-report/app.js:37:132362)
    at e.i (file:///C:/Users/mfaller/Downloads/allure-report/app.js:1:3389)
    at a (file:///C:/Users/mfaller/Downloads/allure-report/app.js:1:3599)
    at file:///C:/Users/mfaller/Downloads/allure-report/app.js:1:3704
    at Function.x.each.x.forEach (file:///C:/Users/mfaller/Downloads/allure-report/app.js:1:77230)
    at o (file:///C:/Users/mfaller/Downloads/allure-report/app.js:1:3655)
    at e.p (file:///C:/Users/mfaller/Downloads/allure-report/app.js:1:4066) undefined
```
```
Uncaught TypeError: Cannot read property 'total' of undefined
    at app.js:37
    at Array.map (<anonymous>)
    at e.value (app.js:37)
    at e.value (app.js:37)
    at app.js:24
```

Firefox includes a different error on each page of the report, including the overview. Possibly relevant?
```
XML Parsing Error: not well-formed
Location: file:///C:/Users/mfaller/Downloads/allure-report/data/categories.json
Line Number 1, Column 1:
```

**Comment by JMoravec** [comment]
I'm running into this as well, to add some more detail: it seems to be because the `widgets.json` file's `"history-trend" object changed with the new cmdline version: it has a mix of items that has the "statistic" object and some that don't (the ones before the upgrade). If I delete all of the ones without the "statistic" object, the report can be viewed just fine served locally.

**Comment by skhomuti** [comment]
We also began to find this error at 2.4 paces for large reports. Is there no solution?
