### ISSUE TITLE
Exception in thread "main" ru.yandex.qatools.allure.data.ReportGenerationException: Could not find any allure results

### ISSUE THREAD

**Issue by PavelStryhelskiIDT** [allure-framework/allure2#761]
Hi,
I`m currently working with automation tests for several projects with C# and Java code.

We use pipelines. 
In the pipelines, there is a command which should generate a report and attach this report to Jenkins.
The command is the following:

************
dir ('A PATH TO A ROOT FOLDER - Debug\ (C#) or build\ (Java)') {
 allure([
                                        includeProperties: true,   (or false - doesn`t matter)
                                        jdk              : '',
                                        properties       : [],
                                        reportBuildPolicy: 'ALWAYS',
                                        results          : [[path: "allure-results"]]
  ])
}
**************

for 'path' I tried a lot of different options:
../allure-results
**/allure-results
and so on.

When using this command, I see the exception:
12:46:11 [build] $ /home/ec2-user/tools/ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation/1.4.23.hotifx/bin/allure generate "/home/ec2-user/workspace/SVP/Automation/SVP_SOAP_Automation/svp-soap/build/allure-results" -o "/home/ec2-user/workspace/SVP/Automation/SVP_SOAP_Automation/svp-soap/build/allure-report"
12:46:13 Exception in thread "main" ru.yandex.qatools.allure.data.ReportGenerationException: Could not find any allure results
12:46:13 	at ru.yandex.qatools.allure.data.AllureReportGenerator.generate(AllureReportGenerator.java:58)
12:46:13 	at ru.yandex.qatools.allure.data.AllureReportGenerator.generate(AllureReportGenerator.java:53)
12:46:13 	at ru.yandex.qatools.allure.AllureMain.main(AllureMain.java:48)
12:46:13 Command aborted due to exception {}.

If I go to slave pc and check the 'build' folder, I`ll see that there is a folder 'allure-results' that has a lot of different .json files. But, the pipeline 'allure {}' command tells me that there are no results.

But at the same time, we can generate reports in 2 ways:
1) in a Gradle project directly - it uses the 'build/allure-results' folder and generates a report successfully
2) if we download a standalone 'allure-2.5.0' zip and use the command  'generate -clean -o' command directly - it works without issues.

But, pipeline allure{} command doesn`t work. It doesn`t work for both C# and Java framework (and both have '../allure-results' 'in the 'Debug\' or 'build\' folders.

Do you have any ideas why this happens?

Can it be because we have some "bad / incorrect " things in frameworks? If so, why can I generate it via a custom standalone command and it works?

Software:
Jenkins ver. 2.60.3
Allure plugin 2.26

**Comment by PavelStryhelskiIDT** [comment]
![image](https://user-images.githubusercontent.com/33135252/37327438-572d136a-26a7-11e8-9078-eb3b96a2eee7.png)
We performed a single gradle test to see if tests are broken or not.
On the screenshot you can see that 'allure-results' dir is not empty
Also, you can see that a report was successfully generated via gradle allure task.
But, allure{} pipeline still shows 'no results' issue.

**Comment by PavelStryhelskiIDT** [comment]
And Windows PC:

![image](https://user-images.githubusercontent.com/33135252/37330781-36a1407e-26b3-11e8-8b46-1ff5ddbb313f.png)

**Comment by PavelStryhelskiIDT** [comment]
UPD:
the problem is solved.
We need to Configure "Allure CommandLine" in Jenkins "Global Tools Configuration" to download the latest version of Allure Command Line.
It is very strange that "1.4.1 version" is set a default one in Jenkins plugin.
