### ISSUE TITLE
NullPointerException while generating allure report

### ISSUE THREAD

**Issue by EugeneGal** [allure-framework/allure2#782]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
Sometimes (1 out of 10 runs) after running a regression with about 200 tests (TestNG runner) against TeamCity and generating allure report through Gradle NullPointerException falls:

> [17:25:09][:allureReport] 	at io.qameta.allure.allure2.Allure2Plugin.getTestStage(Allure2Plugin.java:210)
[17:25:09][:allureReport] 	at io.qameta.allure.allure2.Allure2Plugin.convert(Allure2Plugin.java:91)
[17:25:09][:allureReport] 	at io.qameta.allure.allure2.Allure2Plugin.lambda$readResults$0(Allure2Plugin.java:66)
[17:25:09][:allureReport] 	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
[17:25:09][:allureReport] 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
[17:25:09][:allureReport] 	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
[17:25:09][:allureReport] 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
[17:25:09][:allureReport] 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
[17:25:09][:allureReport] 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
[17:25:09][:allureReport] 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
[17:25:09][:allureReport] 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
[17:25:09][:allureReport] 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
[17:25:09][:allureReport] 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[17:25:09][:allureReport] 	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
[17:25:09][:allureReport] 	at io.qameta.allure.allure2.Allure2Plugin.readResults(Allure2Plugin.java:66)
[17:25:09][:allureReport] 	at io.qameta.allure.ReportGenerator.lambda$readResults$0(ReportGenerator.java:32)
[17:25:09][:allureReport] 	at java.util.ArrayList.forEach(ArrayList.java:1249)
[17:25:09][:allureReport] 	at io.qameta.allure.ReportGenerator.readResults(ReportGenerator.java:32)
[17:25:09][:allureReport] 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
[17:25:09][:allureReport] 	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
[17:25:09][:allureReport] 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
[17:25:09][:allureReport] 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
[17:25:09][:allureReport] 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
[17:25:09][:allureReport] 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
[17:25:09][:allureReport] 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[17:25:09][:allureReport] 	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
[17:25:09][:allureReport] 	at io.qameta.allure.ReportGenerator.generate(ReportGenerator.java:54)
[17:25:09][:allureReport] 	at io.qameta.allure.ReportGenerator.generate(ReportGenerator.java:43)
[17:25:09][:allureReport] 	at io.qameta.allure.Commands.generate(Commands.java:88)
[17:25:09][:allureReport] 	at io.qameta.allure.CommandLine.run(CommandLine.java:129)
[17:25:09][:allureReport] 	at java.util.Optional.orElseGet(Optional.java:267)
[17:25:09][:allureReport] 	at io.qameta.allure.CommandLine.main(CommandLine.java:72)

Settings of xml suite:
`<suite data-provider-thread-count="1" name="Regression Suite" parallel="tests" thread-count="50">`

| Allure version | 2.2.0 |
| --- | --- |
| Test framework | testng@6.9.10 |
| Allure adaptor | allure-testng@2.6.0 |
| Generate report using | allure-gradle:2.5 |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by baev** [comment]
Issue should be fixed in latest versions. Feel free to reopen if problem still exists in 2.9.0
