### ISSUE TITLE
Warning about attempts to (de-)serialize anonymous class appear immediately before agent is killed by OutOfMemoryError

### ISSUE THREAD

**Issue by osmolyar** [allure-framework/allure2#882]
[//]: # (

#### I'm submitting a ... 
  - [ x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?

Warning about attempts to (de-)serialize anonymous class appear immediately before agent is killed by OutOfMemoryError, 'unable to create new native thread', either during or after the 'Creating artifact for the build.' step

-------
Jan 14, 2019 9:27:50 AM org.jenkinsci.remoting.util.AnonymousClassWarnings warn
WARNING: Attempt to (de-)serialize anonymous class ru.yandex.qatools.allure.jenkins.utils.BuildUtils$1; see: https://jenkins.io/redi
rect/serialization-of-anonymous-classes/
Jan 14, 2019 9:27:50 AM org.jenkinsci.remoting.util.AnonymousClassWarnings warn
WARNING: Attempt to (de-)serialize anonymous class ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation$2; see: http
s://jenkins.io/redirect/serialization-of-anonymous-classes/
Jan 14, 2019 9:27:50 AM org.jenkinsci.remoting.util.AnonymousClassWarnings warn
WARNING: Attempt to (de-)serialize anonymous class ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation$1; see: http
s://jenkins.io/redirect/serialization-of-anonymous-classes/
Jan 14, 2019 9:28:40 AM org.jenkinsci.remoting.protocol.impl.BIONetworkLayer$Reader run
SEVERE: [JNLP4-connect connection to qdvmwinselenium/172.17.108.13:63090] Reader thread killed by OutOfMemoryError
java.lang.OutOfMemoryError: unable to create new native thread
        at java.lang.Thread.start0(Native Method)
        at java.lang.Thread.start(Unknown Source)
------
 apparently due to the spawning of thousands of threads, (which should not happen, per https://plumbr.io/outofmemoryerror/unable-to-create-new-native-thread:

"More often than not, the limits on new native threads hit by the OutOfMemoryError indicate a programming error. When your application spawns thousands of threads then chances are that something has gone terribly wrong – there are not many applications out there which would benefit from such a vast amount of threads.
https://plumbr.io/outofmemoryerror/unable-to-create-new-native-thread"

This additionally leads to issue https://github.com/allure-framework/allure2/issues/877, though we have so far found no amount of respources that will resolve the issue.

 
#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
This is reproducible with a 33-test suite, with Jenkins hosted on a Windows 2012R2 VM. (The same setup, with a >1000 test suite, was working earlier with a physical machine hosting Jenkins, with 16GB RAM, 960GB disl space, pagine file 28672Mb.    Not working with the VM with 32GB RAM, 600GB disk space and 28Gb paging file.

#### What is the expected behavior?

Agent does not crash due to 'unable to create new thread' error

#### Please tell us about your environment:
"wdio-cucumber-framework": "^1.1.0",
"wdio-allure-reporter": "^0.7.0",

| --- | --- |
| Generate report using | allure-commandline 2.6.0 |
Allure Jenkins Plugin 2.27.0

Jenkins 2.156
#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by baev** [comment]
@osmolyar what exactly do you want to be resolved during this issue? (having #877 in mind)

**Comment by osmolyar** [comment]
@baev , the main concern is issue #877.  Our entire organization is essentially blocked with using the Jenkins Allure plugin as the agents crash daily and the reports cannot be hosted on Jenkins since they can't be transferred there.

We don't know if it's the warning messages or the extreme fragmentation of the zip artifact that is the real issue.   As mentioned in #877, we are totally fine with eliminating all the request/response items in the report unless they contain an attachment, stack trace or assertion error.

**Comment by baev** [comment]
@osmolyar I mean can we close this issue and keep everything in #877 ?

**Comment by osmolyar** [comment]
@baev , yes, that is fine, thank you.
