### ISSUE TITLE
Could not read test result file

### ISSUE THREAD

**Issue by Ljancek** [allure-framework/allure2#915]
**Describe the bug**
Allure generate report failing on error "Could not read test result file"

**To Reproduce**
1. Run test
2. try generate report

**Expected behavior**
Report should be generated

**Screenshots**

**Environment (please complete the following information):**

| Allure version | 2.10.0 |
| --- | --- |
| Test framework | behave@1.2.7 |-e git+git://github.com/xrg/behave-parallel.git@eparallel#egg=behave-parallel|
                           |allure-behave@2.6.0 |
                           |allure-python-commons@2.6.0 |
| Allure adaptor | allure-testng@2.10.0 |

**Additional context**
`Could not read test result file allure-results/d98b4e96-3fd8-4497-9cb5-d6e506006390-result.json
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.lang.String` out of START_ARRAY token
 at [Source: (sun.nio.ch.ChannelInputStream); line: 1, column: 194] (through reference chain: io.qameta.allure.model.TestResult["statusDetails"]->io.qameta.allure.model.StatusDetails["trace"])
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1343)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1139)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer._deserializeFromArray(StdDeserializer.java:675)
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:40)
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:10)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3070)
	at io.qameta.allure.allure2.Allure2Plugin.readTestResult(Allure2Plugin.java:344)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at io.qameta.allure.allure2.Allure2Plugin.readResults(Allure2Plugin.java:104)
	at io.qameta.allure.ReportGenerator.lambda$readResults$0(ReportGenerator.java:47)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at io.qameta.allure.ReportGenerator.readResults(ReportGenerator.java:47)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at io.qameta.allure.ReportGenerator.generate(ReportGenerator.java:69)
	at io.qameta.allure.ReportGenerator.generate(ReportGenerator.java:58)
	at io.qameta.allure.Commands.generate(Commands.java:105)
	at io.qameta.allure.CommandLine.run(CommandLine.java:152)
	at java.util.Optional.orElseGet(Optional.java:267)
	at io.qameta.allure.CommandLine.main(CommandLine.java:88)`

**Comment by Ljancek** [comment]
Any update?

**Comment by ervuks** [comment]
Looks like there is unsuccessful deserialization which leads to this issue. 
I've found a possible line of the cause: https://github.com/allure-framework/allure2/blob/master/allure-generator/src/main/java/io/qameta/allure/allure2/Allure2Plugin.java#L342

**Comment by Ljancek** [comment]
Do you have any idea when will be fixed it?

**Comment by ervuks** [comment]
> Do you have any idea when will be fixed it?

I could try to fix this, but I will need an example of a report file to reproduce this issue, write tests and verify.

**Comment by Ljancek** [comment]
@ervuks sry for very late reaction. 

here is the result of failing to generate a report (rename txt to json :-) ) 
[21c0dd3a-a8b6-48a1-8a55-8f6ee1e91fec-result.txt](https://github.com/allure-framework/allure2/files/3195603/21c0dd3a-a8b6-48a1-8a55-8f6ee1e91fec-result.txt)
![0443dd14-5300-4f60-9160-e21fbacfaabd-attachment](https://user-images.githubusercontent.com/44829911/57987978-d2a9e000-7a88-11e9-9bef-e71052d8920e.png)
