### ISSUE TITLE
add   @Author  with testng

### ISSUE THREAD

**Issue by xian-crazy** [allure-framework/allure2#916]
**add   @Author  with testng  like these：**

     @Test
     @Story(DEMO.Epic1Feature1Story2)
     @Description("my description")
     @Severity(SeverityLevel.MINOR)
     @Author("the author name")
     public void mycase(){
         Assert.assertNull(null);
     }

**in report, add chart  in graph for Author like the DURATION in report: **

the x axis is author  ，the y axis is the count of case  by author

**in report,add tap for author like behaviors **

like behaviors,but the root node is the author  ,and sub node like behaviors

**Comment by xian-crazy** [comment]
I found that Owner annotations can show authors in reports.

and then  ,I have write the author plug-in  base  the package plug-in and , which can be displayed according to the author statistics.
[superdes-plugin.zip](https://github.com/allure-framework/allure2/files/3105493/superdes-plugin.zip)

**Comment by xian-crazy** [comment]
# 用例作者注解
方法1：测试类注解

    @Owner("author name")
    public class MyTestClass{...

方法2：测试方法注解

    @Test
    @Owner("author name")
    public void myCase(...

方法3：内部注解

    @Test
    public void myCase(){
    Allure.label("owner","author name");
    // TO DO
    }

then the owner tab
will be find in the report like the image
![QQ截图20190423101147](https://user-images.githubusercontent.com/6520452/56547511-45ba5680-65b0-11e9-9ce3-a1fe507a7e1c.png)

**Comment by shaikhaziz** [comment]
@xian-crazy  I added the plugin in the plugin folder & made the changes in main yaml file.
but I am getting this when i run allure generate.
Exception in thread "main" java.lang.NoSuchMethodError: 'java.lang.Object io.qameta.allure.core.Configuration.requireContext(java.lang.Class)'
        at com.quvideo.servertest.allure.AuthorPlugin.aggregate(AuthorPlugin.java:38)
        at io.qameta.allure.ReportGenerator.processOldAggregators(ReportGenerator.java:75)
        at io.qameta.allure.ReportGenerator.aggregate(ReportGenerator.java:60)
        at io.qameta.allure.ReportGenerator.generate(ReportGenerator.java:121)
        at io.qameta.allure.ReportGenerator.generate(ReportGenerator.java:103)
        at io.qameta.allure.Commands.generate(Commands.java:113)
        at io.qameta.allure.CommandLine.run(CommandLine.java:160)
        at java.base/java.util.Optional.orElseGet(Optional.java:369)
        at io.qameta.allure.CommandLine.main(CommandLine.java:92)

![Screenshot from 2024-01-15 17-50-57](https://github.com/allure-framework/allure2/assets/22943072/fe1a02c0-3e79-4bb5-a411-7987765de5cf)
