### ISSUE TITLE
Error when generates a report - Allure Test Reports(Molecula) plugin - Azure Devops(VSTS)

### ISSUE THREAD

**Issue by fescobar** [allure-framework/allure2#919]
**Describe the bug**
I'm using this plugin for Allure
https://marketplace.visualstudio.com/items?itemName=Molecula.allure-test-reports
When Azure try to generate the report throws next errors

For `Ubuntu` agent:
```
[command]/usr/local/bin/node /home/vsts/work/_tasks/AllureGenerate_5c975f9d-1c3a-469f-b7c2-8907bf3eacfb/1.0.0/node_modules/allure-commandline/bin/allure generate --output /home/vsts/work/1/s/allure-report/46 /home/vsts/work/1/s/allure-results
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn /home/vsts/work/_tasks/AllureGenerate_5c975f9d-1c3a-469f-b7c2-8907bf3eacfb/1.0.0/node_modules/allure-commandline/dist/bin/allure EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
      throw er; // Unhandled 'error' event
      ^

Error: spawn /home/vsts/work/_tasks/AllureGenerate_5c975f9d-1c3a-469f-b7c2-8907bf3eacfb/1.0.0/node_modules/allure-commandline/dist/bin/allure EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
```

For `Windows` agent:
```
[command]C:\Program Files\nodejs\node.exe D:\a\_tasks\AllureGenerate_5c975f9d-1c3a-469f-b7c2-8907bf3eacfb\1.0.0\node_modules\allure-commandline\bin\allure generate --output D:\a\1\s\allure-report\49 D:\a\1\s\allure-results
Command aborted due to exception {}.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:153)
	at ru.yandex.qatools.allure.command.ReportGenerate.runUnsafe(ReportGenerate.java:48)
	at ru.yandex.qatools.allure.command.AbstractCommand.run(AbstractCommand.java:52)
	at ru.yandex.qatools.allure.CommandLine.main(CommandLine.java:46)
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:153)
	at ru.yandex.qatools.allure.command.ReportGenerate.runUnsafe(ReportGenerate.java:48)
	at ru.yandex.qatools.allure.command.AbstractCommand.run(AbstractCommand.java:52)
	at ru.yandex.qatools.allure.CommandLine.main(CommandLine.java:46)

	at ru.yandex.qatools.allure.data.AllureReportGenerator.generate(AllureReportGenerator.java:58)
	at ru.yandex.qatools.allure.data.AllureReportGenerator.generate(AllureReportGenerator.java:53)
	at ru.yandex.qatools.allure.AllureMain.main(AllureMain.java:48)

Exception in thread "main" ru.yandex.qatools.allure.data.ReportGenerationException: Could not find any allure results
	at ru.yandex.qatools.allure.data.AllureReportGenerator.generate(AllureReportGenerator.java:58)
	at ru.yandex.qatools.allure.data.AllureReportGenerator.generate(AllureReportGenerator.java:53)
	at ru.yandex.qatools.allure.AllureMain.main(AllureMain.java:48)
```

**To Reproduce**
1. Go to Azure Devops
2. Install Allure plugin https://marketplace.visualstudio.com/items?itemName=Molecula.allure-test-reports
3. Go to your Azure project according to your user/workspace.
4. Go to `Pipeline` section
5. Create a new pipeline.
6. Setup a build with Ubuntu/Windows (according what error you need to reproduce) agent
![image](https://user-images.githubusercontent.com/1236418/54749220-c9f17680-4bcb-11e9-8310-cb25cbee53b3.png)
7. Setup any project to generate results (In this case Maven/Java project)
8. Setup sheel script for Ubuntu agent to verify files in `allure-results` directory (use CMD for Windows)
![image](https://user-images.githubusercontent.com/1236418/54749258-e8f00880-4bcb-11e9-9164-26118e3dd84d.png)
9. Setup allure plugin to take `allure-results` directory to generate a report.
![image](https://user-images.githubusercontent.com/1236418/54749276-f3120700-4bcb-11e9-921a-4b4a52f9b426.png)

10. Run pipeline

**Expected behavior**
When pipeline finished (failed or not), it should generate Allure report files.

**Screenshots**
**Error for Ubuntu**
Verifying if `allure-results` directory exists and if it contains files results.
![image](https://user-images.githubusercontent.com/1236418/54749587-eb9f2d80-4bcc-11e9-9051-61d02b46d18b.png)

Stack trace when Allure plugin is trying to generate a report.
![image](https://user-images.githubusercontent.com/1236418/54749626-1093a080-4bcd-11e9-9977-c58634b699a5.png)

**Error for Windows**
Verifying if `allure-results` directory exists and if it contains files results.
![image](https://user-images.githubusercontent.com/1236418/54750330-36ba4000-4bcf-11e9-9148-b462bf6b5d5e.png)

Stack trace when Allure plugin is trying to generate a report.
![image](https://user-images.githubusercontent.com/1236418/54750354-433e9880-4bcf-11e9-8643-f13bcf534916.png)

**Comment by MegalaRajendran** [comment]
Facing the same issue. Do we have any updates?

**Comment by fescobar** [comment]
@MegalaRajendran seems to be nobody is maintaining this plugin.

I have another solution for you. You could start up an Allure docker container in your server  (**Allure Docker Service:** https://github.com/fescobar/allure-docker-service ) and you could send your results from **AzureDevops** to that container through API.

https://github.com/fescobar/allure-docker-service#send-results-through-api

**Comment by MegalaRajendran** [comment]
@fescobar  Thanks for workaround. Will Try . Hope this solves

**Comment by stambecg** [comment]
Hi Team,

Allure Test Reports plugin is not working on Azure, i am getting below error.
Could you please look into it?

I have checked C:\agent_work\2\s\target\allure-results contains multiple files

2020-02-12T09:42:21.9156093Z ##[section]Starting: Generate Allure Report
2020-02-12T09:42:22.0589528Z ==============================================================================
2020-02-12T09:42:22.0589617Z Task : Generate Allure Report
2020-02-12T09:42:22.0589645Z Description : Generates Allure report based on the test results
2020-02-12T09:42:22.0589673Z Version : 1.0.0
2020-02-12T09:42:22.0589697Z Author : Molecula
2020-02-12T09:42:22.0589727Z Help : More Information
2020-02-12T09:42:22.0589752Z ==============================================================================
2020-02-12T09:42:22.9191463Z [command]C:\Program Files\nodejs\node.exe C:\agent_work_tasks\AllureGenerate_5c975f9d-1c3a-469f-b7c2-8907bf3eacfb\1.0.0\node_modules\allure-commandline\bin\allure generate --output C:\agent_work\2\s\allure-report\20200212.10 C:\agent_work\2\s\target\allure-results
2020-02-12T09:42:26.9963352Z Command aborted due to exception {}.

2020-02-12T09:42:26.9963671Z Exception in thread "main" ru.yandex.qatools.allure.data.ReportGenerationException: Could not find any allure results

2020-02-12T09:42:26.9963753Z org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)

2020-02-12T09:42:26.9963833Z at ru.yandex.qatools.allure.data.AllureReportGenerator.generate(AllureReportGenerator.java:58)
2020-02-12T09:42:26.9963900Z at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
2020-02-12T09:42:26.9964290Z at ru.yandex.qatools.allure.data.AllureReportGenerator.generate(AllureReportGenerator.java:53)
2020-02-12T09:42:26.9964350Z at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
2020-02-12T09:42:26.9964634Z at ru.yandex.qato

**Comment by fescobar** [comment]
@stambecg Nobody is maintaining this plugin.

**Comment by Garynychxxx** [comment]
Could you help me with advice on best way to attach a report to each azure work through ALLURE DOCKER SERVICE. Thanks for your work

**Comment by fescobar** [comment]
@Garynychxxx Allure Docker Service exposes an API. For example, you can send results from anywhere even from Azure. You can deploy 1 or multiple allure docker containers, it's up to you. But this solution is outside of Azure, you have to have your own infrastructure.

Another option is to run allure docker command in azure including your results to generate the emailable report https://github.com/fescobar/allure-docker-service#customize-emailable-report, after that you should stop the container.

You have multiple ways to use that container, it's up to you what is the best way in your case. You have all the documentation here https://github.com/fescobar/allure-docker-service

**Comment by Garynychxxx** [comment]
> @Garynychxxx Allure Docker Service exposes an API. For example, you can send results from anywhere even from Azure. You can deploy 1 or multiple allure docker containers, it's up to you. But this solution is outside of Azure, you have to have your own infrastructure.
> 
> Another option is to run allure docker command in azure including your results to generate the emailable report https://github.com/fescobar/allure-docker-service#customize-emailable-report, after that you should stop the container.
> 
> You have multiple ways to use that container, it's up to you what is the best way in your case. You have all the documentation here https://github.com/fescobar/allure-docker-service

Yep thanks, But as I understand it is impossible to create individual report for each job .
Something like this.....


![Untitled](https://user-images.githubusercontent.com/26542795/76226193-93729880-622e-11ea-8163-c38507d238b5.png)

**Comment by fescobar** [comment]
@Garynychxxx Use a different port for a different group of tests or categorize your tests.

**Comment by Garynychxxx** [comment]
> @Garynychxxx Use a different port for a different group of tests or categorize your tests.


Is your project intended for local use only? I tried to run it on azure and could not open the API.

http://alluressreport.azurewebsites.net/index.html

**Comment by fescobar** [comment]
@Garynychxxx you can use it from everywhere, even from kubernetes. You need to expose the API (use different port, by default 5050). Read the doc https://github.com/fescobar/allure-docker-service#allure-api

**Comment by khanzzirfan** [comment]
Same issues as orginally posted. Does this plugin ever works ?
I copied results through script to allure-reports/buildId folder.  still dont see allure showing reports on the finished build pipeline

**Comment by mihaivilcufd** [comment]
Same issue seen as in the original post. :(

**Comment by MikhailTamarinFlipdish** [comment]
Here is the fix. There are two ways depending on agent you are using.
1) Use Azure Pipelines - vs2017-win2016 agent
2) Use any Linux agent (Azure Pipelines Ubuntu or self hosted) with extra task before creating Allure Report
`chmod 755 $(Agent.WorkFolder)/_tasks/AllureGenerate_5c975f9d-1c3a-469f-b7c2-8907bf3eacf1/1.0.0/node_modules/allure-commandline/dist/bin/allure`

**Comment by SomeOne55468** [comment]
As described above on Pipeline add an extra task (Bash) before creating Allure Report and add these lines
```
sed -i 's/allure-commandline.*/allure-commandline\": \">=2.13.8",/' $(Agent.WorkFolder)/_tasks/AllureGenerate_5c975f9d-1c3a-469f-b7c2-8907bf3eacfb/1.0.0/package.json
cd $(Agent.WorkFolder)/_tasks/AllureGenerate_5c975f9d-1c3a-469f-b7c2-8907bf3eacfb/1.0.0/ && npm update
chmod -R 777 $(Agent.WorkFolder)/_tasks/AllureGenerate_5c975f9d-1c3a-469f-b7c2-8907bf3eacfb/1.0.0/
chmod 755 $(Agent.WorkFolder)/_tasks/AllureGenerate_5c975f9d-1c3a-469f-b7c2-8907bf3eacfb/1.0.0/node_modules/allure-commandline/dist/bin/allure
```
If something is not working check Dir is exists( i mean AllureGenerate_**5c975f9d-1c3a-469f-b7c2-8907bf3eacfb**)!

**Comment by ElkRom** [comment]
Will someone fix this issue?

**Comment by fescobar** [comment]
@ElkRom I don't think so.

**Comment by uLucasFraga** [comment]
Hey, are will still without standard solution? :(

**Comment by Madiha20** [comment]
@MikhailTamarinFlipdish 
Can you please guide if below is correct? I am getting an error as no such file or dir.

<img width="1007" alt="image" src="https://user-images.githubusercontent.com/88466826/235451714-eb9a35b1-789b-4675-aa2b-805d3b795cb8.png">

**Comment by MikhailTamarinFlipdish** [comment]
> @MikhailTamarinFlipdish Can you please guide if below is correct? I am getting an error as no such file or dir.
> 
> <img alt="image" width="1007" src="https://user-images.githubusercontent.com/88466826/235451714-eb9a35b1-789b-4675-aa2b-805d3b795cb8.png">

`find $(Agent.WorkFolder)/_tasks/ -name allure -type f -exec chmod 755 {} \;`
This is the command we are executing before AllureGenerate task. Works like a charm.

**Comment by Madiha20** [comment]
@MikhailTamarinFlipdish 
Thanks, the bash job worked but now getting a different error for generating the report. Looks like i am pretty close. 

This is how I am generating report via script in package.json file

`"generate": "allure generate --clean allure-results"`

Pipeline
```
# Script to run the automation tests
- script: |
    ENV=${{ parameters.environment }} npm run test
    npm run generate
    if [ $? -ne 0 ]; then
        exit 1
  displayName: 'Run Tests'

# Copy the target folder to Azure Pipelines
- task: CopyFiles@2
  condition: succeededOrFailed()
  inputs:
    Contents: 'allure-report/**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

# Publish build artifacts to Azure Pipelines
- task: PublishPipelineArtifact@1
  condition: succeededOrFailed()
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    publishLocation: 'pipeline'

- task: Bash@3
  condition: succeededOrFailed()
  inputs:
    targetType: 'inline'
    script: chmod 755 $(Agent.WorkFolder)/_tasks/AllureGenerate_5c975f9d-1c3a-469f-b7c2-8907bf3eacfb/1.0.0/node_modules/allure-commandline/dist/bin/allure

# Publish Allure report to Azure Pipelines
- task: AllureGenerate@1
  condition: succeededOrFailed()
  inputs:
    resultsDir: 'allure-results'
    targetDir: 'allure-report/$(Build.BuildNumber)'
```

<img width="1107" alt="image" src="https://user-images.githubusercontent.com/88466826/235452855-8b76c62b-c659-4bef-922d-8a6c904bd060.png">

**Comment by Madiha20** [comment]
@MikhailTamarinFlipdish 
Can you please confirm if your report is generated at this URL as there is a difference of path and I think that is why the report is not getting generated. 

<img width="883" alt="image" src="https://user-images.githubusercontent.com/88466826/235457019-48a6e468-5f1e-4456-9740-0349a460421e.png">

**Comment by baev** [comment]
see https://github.com/allure-framework/allure2/issues/1140

**Comment by baev** [comment]
Official Allure extension for Azure Pipelines are now available https://marketplace.visualstudio.com/items?itemName=qameta.allure-azure-pipelines

History isn't yet supported, but we'll get there! Please submit feedback to our [discussions](https://github.com/orgs/allure-framework/discussions)
