### ISSUE TITLE
allure-report  xray plugin -> "Expected URL scheme 'http' or 'https' but no colon was found"

### ISSUE THREAD

**Issue by mcpabst** [allure-framework/allure2#929]
**Describe the bug**
By running allure-report with xray Plug-In 

**To Reproduce**
1. Set up Jenkins (on windows)
2. Install Plugins -> Allure report + 
4. [test] $ "C:\Program Files (x86)\Jenkins\tools\ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation\allure\bin\allure.bat" generate "C:\Program Files (x86)\Jenkins\workspace\test\target\allure-results" -c -o "C:\Program Files (x86)\Jenkins\workspace\test\allure-report"
Exception in thread "main" java.lang.IllegalArgumentException: Expected URL scheme 'http' or 'https' but no colon was found
	at okhttp3.HttpUrl$Builder.parse(HttpUrl.java:1333)
	at okhttp3.HttpUrl.get(HttpUrl.java:916)
	at retrofit2.Retrofit$Builder.baseUrl(Retrofit.java:458)
	at io.qameta.allure.jira.JiraServiceBuilder.build(JiraServiceBuilder.java:73)
	at io.qameta.allure.xray.XrayTestRunExportPlugin.lambda$new$0(XrayTestRunExportPlugin.java:77)
	at io.qameta.allure.xray.XrayTestRunExportPlugin.updateTestRunStatuses(XrayTestRunExportPlugin.java:102)
	at io.qameta.allure.xray.XrayTestRunExportPlugin.aggregate(XrayTestRunExportPlugin.java:96)
	at io.qameta.allure.ReportGenerator.aggregate(ReportGenerator.java:53)
	at io.qameta.allure.ReportGenerator.generate(ReportGenerator.java:70)
	at io.qameta.allure.ReportGenerator.generate(ReportGenerator.java:58)
	at io.qameta.allure.Commands.generate(Commands.java:105)
	at io.qameta.allure.CommandLine.run(CommandLine.java:152)
	at java.util.Optional.orElseGet(Optional.java:267)
	at io.qameta.allure.CommandLine.main(CommandLine.java:88)
ERROR: Build step failed with exception
ru.yandex.qatools.allure.jenkins.exception.AllurePluginException: Can not generate Allure Report, exit code: 1
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.generateReport(AllureReportPublisher.java:314)
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.perform(AllureReportPublisher.java:231)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1841)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Build step 'Allure Report' marked build as failure
Finished: FAILURE

**Expected behavior**
Results for Allure will be generated

**Screenshots**

**Environment (please complete the following information):**
Jenkins
Allure Jenkins Plugin 2.28.1

**Comment by baev** [comment]
closed as stale
