### ISSUE TITLE
Mocha+Allure 'Internal error in Allure: Error: charData should not contain characters not allowed in XML' whe

### ISSUE THREAD

**Issue by akarasenko** [allure-framework/allure2#991]
**Describe the bug**
I use: JavaScript+Mocha+Allure
`"dependencies": {
    "allure-mocha": "^2.0.0-beta.4",
    "mocha": "^5.2.0",
    "mocha-allure-reporter": "^1.4.0"
}`
When assertion fails (actual result is not equal to expected) generating XML result throws an error:
`Internal error in Allure: Error: charData should not contain characters not allowed in XML
    at XmlCharData.set [as charData] (C:\test\node_modules\xmlcreate\lib\nodes\XmlCharData.js:75:23)
    at new XmlCharData (C:\test\node_modules\xmlcreate\lib\nodes\XmlCharData.js:53:24)
    at XmlElement.charData (C:\test\node_modules\xmlcreate\lib\nodes\XmlElement.js:168:28)
    at parseString (C:\test\node_modules\js2xmlparser\lib\main.js:53:27)
    at parseValue (C:\test\node_modules\js2xmlparser\lib\main.js:227:5)
    at parseObjectOrMapEntry (C:\test\node_modules\js2xmlparser\lib\main.js:132:5)
    at parseObjectOrMap (C:\test\node_modules\js2xmlparser\lib\main.js:152:13)
    at parseValue (C:\test\node_modules\js2xmlparser\lib\main.js:220:9)
    at parseObjectOrMapEntry (C:\test\node_modules\js2xmlparser\lib\main.js:132:5)
    at parseObjectOrMap (C:\test\node_modules\js2xmlparser\lib\main.js:152:13)
    at parseValue (C:\test\node_modules\js2xmlparser\lib\main.js:220:9)
    at C:\test\node_modules\js2xmlparser\lib\main.js:192:9
    at Array.forEach (<anonymous>)
    at parseArrayOrSet (C:\test\node_modules\js2xmlparser\lib\main.js:187:16)
    at parseValue (C:\test\node_modules\js2xmlparser\lib\main.js:224:9)
    at parseObjectOrMapEntry (C:\test\node_modules\js2xmlparser\lib\main.js:132:5)
    at parseObjectOrMap (C:\test\node_modules\js2xmlparser\lib\main.js:152:13)
    at parseValue (C:\test\node_modules\js2xmlparser\lib\main.js:220:9)
    at parseObjectOrMapEntry (C:\test\node_modules\js2xmlparser\lib\main.js:132:5)
    at parseObjectOrMap (C:\test\node_modules\js2xmlparser\lib\main.js:152:13)
    at parseValue (C:\test\node_modules\js2xmlparser\lib\main.js:220:9)
    at parseToDocument (C:\test\node_modules\js2xmlparser\lib\main.js:249:5)
    at Object.parse (C:\test\node_modules\js2xmlparser\lib\main.js:265:20)
    at Object.writeSuite (C:\test\node_modules\mocha-allure-reporter\node_modules\allure-js-commons\writer.js:9:83)
    at Allure.endSuite (C:\test\node_modules\mocha-allure-reporter\node_modules\allure-js-commons\index.js:36:16)
    at Runner.<anonymous> (C:\test\node_modules\mocha-allure-reporter\index.js:35:24)
    at Runner.<anonymous> (C:\test\node_modules\mocha-allure-reporter\index.js:23:32)
    at Runner.emit (events.js:203:15)
    at C:\test\node_modules\mocha\lib\runner.js:771:14
    at next (C:\test\node_modules\mocha\lib\runner.js:362:14)
    at Immediate._onImmediate (C:\test\node_modules\mocha\lib\runner.js:425:5)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)`
Failed test doesn't included in testing report.

This happens eve for simplest test with only assertion:
`it('Test failure', function () {
    assert.strictEqual(1, 2);
});`

**Expected behavior**
No errors while generation XML report. Failed test is included into report and marked as failed with assertion details.

**Environment:**
| Test framework | mocha@5.2.0 |
| Allure adaptor | allure-mocha@2.0.0-beta.4 |
| Generate report using |mocha-allure-reporter@1.4.0|

**Comment by baev** [comment]
`mocha-allure-reporter` is the old version (that uses XML to store results) of Allure Mocha integration. The new one is `allure-mocha` (new API, uses JSON instead of XML to store results). You should consider migration from `mocha-allure-reporter` to allure-mocha` in order to fix the problem

**Comment by akarasenko** [comment]
Thank you @baev !

This helps.
There are examples of using mocha-allure-reporter in documentation:
https://docs.qameta.io/allure/#_mocha
https://github.com/allure-framework/allure-mocha
This is a bit confusing about actual version.
